CREATE TABLE `game_pet_catalog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`description` text,
	`race` varchar(30) NOT NULL DEFAULT 'normal',
	`wuxing` varchar(20) NOT NULL DEFAULT 'earth',
	`rarity` varchar(20) NOT NULL DEFAULT 'common',
	`growth_type` varchar(20) NOT NULL DEFAULT 'balanced',
	`base_bp_constitution` int NOT NULL DEFAULT 20,
	`base_bp_strength` int NOT NULL DEFAULT 20,
	`base_bp_defense` int NOT NULL DEFAULT 20,
	`base_bp_agility` int NOT NULL DEFAULT 20,
	`base_bp_magic` int NOT NULL DEFAULT 20,
	`race_hp_multiplier` float NOT NULL DEFAULT 1,
	`min_level` int NOT NULL DEFAULT 1,
	`max_level` int NOT NULL DEFAULT 50,
	`base_capture_rate` int NOT NULL DEFAULT 30,
	`image_url` text,
	`is_active` tinyint NOT NULL DEFAULT 1,
	`sort_order` int NOT NULL DEFAULT 0,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `game_pet_catalog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `game_pet_innate_skills` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pet_catalog_id` int NOT NULL,
	`name` varchar(100) NOT NULL,
	`description` text,
	`skill_type` varchar(20) NOT NULL DEFAULT 'attack',
	`wuxing` varchar(20),
	`power_percent` int NOT NULL DEFAULT 100,
	`mp_cost` int NOT NULL DEFAULT 5,
	`cooldown` int NOT NULL DEFAULT 2,
	`unlock_level` int NOT NULL DEFAULT 1,
	`slot_index` int NOT NULL DEFAULT 1,
	`sort_order` int NOT NULL DEFAULT 0,
	`created_at` bigint NOT NULL,
	CONSTRAINT `game_pet_innate_skills_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `game_pet_learned_skills` (
	`id` int AUTO_INCREMENT NOT NULL,
	`player_pet_id` int NOT NULL,
	`skill_name` varchar(100) NOT NULL,
	`skill_type` varchar(20) NOT NULL DEFAULT 'attack',
	`skill_key` varchar(50) NOT NULL,
	`wuxing` varchar(20),
	`power_percent` int NOT NULL DEFAULT 100,
	`mp_cost` int NOT NULL DEFAULT 8,
	`cooldown` int NOT NULL DEFAULT 3,
	`skill_level` int NOT NULL DEFAULT 1,
	`usage_count` int NOT NULL DEFAULT 0,
	`slot_index` int NOT NULL DEFAULT 4,
	`is_equipped` tinyint NOT NULL DEFAULT 1,
	`learned_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `game_pet_learned_skills_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `game_player_pets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`agent_id` int NOT NULL,
	`pet_catalog_id` int NOT NULL,
	`nickname` varchar(100),
	`level` int NOT NULL DEFAULT 1,
	`exp` int NOT NULL DEFAULT 0,
	`tier` varchar(5) NOT NULL DEFAULT 'C',
	`bp_constitution` int NOT NULL DEFAULT 20,
	`bp_strength` int NOT NULL DEFAULT 20,
	`bp_defense` int NOT NULL DEFAULT 20,
	`bp_agility` int NOT NULL DEFAULT 20,
	`bp_magic` int NOT NULL DEFAULT 20,
	`hp` int NOT NULL DEFAULT 50,
	`max_hp` int NOT NULL DEFAULT 50,
	`mp` int NOT NULL DEFAULT 30,
	`max_mp` int NOT NULL DEFAULT 30,
	`attack` int NOT NULL DEFAULT 10,
	`defense` int NOT NULL DEFAULT 10,
	`speed` int NOT NULL DEFAULT 10,
	`magic_attack` int NOT NULL DEFAULT 10,
	`growth_type` varchar(20) NOT NULL DEFAULT 'balanced',
	`is_active` tinyint NOT NULL DEFAULT 0,
	`friendship` int NOT NULL DEFAULT 0,
	`captured_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `game_player_pets_id` PRIMARY KEY(`id`)
);
