CREATE TABLE `roaming_boss_catalog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`boss_code` varchar(50) NOT NULL,
	`name` varchar(100) NOT NULL,
	`title` varchar(100),
	`tier` int NOT NULL DEFAULT 1,
	`wuxing` varchar(10) NOT NULL,
	`level` int NOT NULL DEFAULT 30,
	`base_hp` int NOT NULL DEFAULT 5000,
	`base_attack` int NOT NULL DEFAULT 80,
	`base_defense` int NOT NULL DEFAULT 40,
	`base_speed` int NOT NULL DEFAULT 25,
	`base_magic_attack` int NOT NULL DEFAULT 60,
	`base_magic_defense` int NOT NULL DEFAULT 30,
	`skills` json,
	`drop_table` json,
	`exp_multiplier` float NOT NULL DEFAULT 2,
	`gold_multiplier` float NOT NULL DEFAULT 2,
	`move_interval_sec` int NOT NULL DEFAULT 300,
	`lifetime_minutes` int NOT NULL DEFAULT 0,
	`stamina_cost` int NOT NULL DEFAULT 15,
	`patrol_region` json,
	`spawn_node_id` varchar(50),
	`image_url` text,
	`description` text,
	`enrage_config` json,
	`is_active` tinyint NOT NULL DEFAULT 1,
	`schedule_config` json,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `roaming_boss_catalog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `roaming_boss_instances` (
	`id` int AUTO_INCREMENT NOT NULL,
	`catalog_id` int NOT NULL,
	`current_node_id` varchar(50) NOT NULL,
	`move_history` json,
	`current_hp` int NOT NULL DEFAULT -1,
	`status` varchar(20) NOT NULL DEFAULT 'active',
	`spawned_at` bigint NOT NULL,
	`expires_at` bigint NOT NULL DEFAULT 0,
	`last_moved_at` bigint NOT NULL,
	`defeated_by` json,
	`is_first_kill` tinyint NOT NULL DEFAULT 0,
	`challenge_count` int NOT NULL DEFAULT 0,
	CONSTRAINT `roaming_boss_instances_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `roaming_boss_kill_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`instance_id` int NOT NULL,
	`catalog_id` int NOT NULL,
	`agent_id` int NOT NULL,
	`agent_name` varchar(100) NOT NULL,
	`result` varchar(20) NOT NULL,
	`damage_dealt` int NOT NULL DEFAULT 0,
	`rounds` int NOT NULL DEFAULT 0,
	`exp_gained` int NOT NULL DEFAULT 0,
	`gold_gained` int NOT NULL DEFAULT 0,
	`drops_gained` json,
	`is_first_kill` tinyint NOT NULL DEFAULT 0,
	`node_id` varchar(50) NOT NULL,
	`battle_at` bigint NOT NULL,
	CONSTRAINT `roaming_boss_kill_log_id` PRIMARY KEY(`id`)
);
