ALTER TABLE `game_agents` ADD `mdef` int DEFAULT 10 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_agents` ADD `spr` int DEFAULT 10 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_agents` ADD `crit_rate` float DEFAULT 5 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_agents` ADD `crit_damage` float DEFAULT 150 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_agents` ADD `realm` varchar(10) DEFAULT '初界' NOT NULL;--> statement-breakpoint
ALTER TABLE `game_agents` ADD `profession` varchar(20) DEFAULT 'none' NOT NULL;--> statement-breakpoint
ALTER TABLE `game_agents` ADD `profession_tier` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_agents` ADD `fate_element` varchar(10) DEFAULT 'wood' NOT NULL;--> statement-breakpoint
ALTER TABLE `game_equipment_catalog` ADD `mp_bonus` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_equipment_catalog` ADD `magic_attack_bonus` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_equipment_catalog` ADD `magic_defense_bonus` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_equipment_catalog` ADD `heal_power_bonus` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_equipment_catalog` ADD `crit_rate_bonus` float DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_equipment_catalog` ADD `crit_damage_bonus` float DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_monster_catalog` ADD `base_mp` int DEFAULT 30 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_monster_catalog` ADD `base_magic_defense` int DEFAULT 5 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_monster_catalog` ADD `base_heal_power` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_monster_catalog` ADD `base_crit_rate` float DEFAULT 5 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_monster_catalog` ADD `base_crit_damage` float DEFAULT 150 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_monster_catalog` ADD `wuxing_wood` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_monster_catalog` ADD `wuxing_fire` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_monster_catalog` ADD `wuxing_earth` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_monster_catalog` ADD `wuxing_metal` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_monster_catalog` ADD `wuxing_water` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_monster_catalog` ADD `realm` varchar(10) DEFAULT '初界' NOT NULL;--> statement-breakpoint
ALTER TABLE `game_monster_catalog` ADD `realm_multiplier` float DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_monster_catalog` ADD `species` varchar(20) DEFAULT 'beast' NOT NULL;--> statement-breakpoint
ALTER TABLE `game_pet_catalog` ADD `wuxing_wood` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_pet_catalog` ADD `wuxing_fire` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_pet_catalog` ADD `wuxing_earth` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_pet_catalog` ADD `wuxing_metal` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_pet_catalog` ADD `wuxing_water` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_pet_catalog` ADD `base_magic_defense` int DEFAULT 5 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_pet_catalog` ADD `base_heal_power` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_pet_catalog` ADD `species` varchar(20) DEFAULT 'beast' NOT NULL;--> statement-breakpoint
ALTER TABLE `game_player_pets` ADD `magic_defense` int DEFAULT 5 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_player_pets` ADD `heal_power` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_player_pets` ADD `wuxing_wood` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_player_pets` ADD `wuxing_fire` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_player_pets` ADD `wuxing_earth` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_player_pets` ADD `wuxing_metal` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_player_pets` ADD `wuxing_water` int DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_player_pets` ADD `species` varchar(20) DEFAULT 'beast' NOT NULL;--> statement-breakpoint
ALTER TABLE `game_player_pets` ADD `realm` varchar(10) DEFAULT '初界' NOT NULL;--> statement-breakpoint
ALTER TABLE `game_skill_catalog` ADD `wuxing_threshold` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_skill_catalog` ADD `status_effect` varchar(20) DEFAULT 'none' NOT NULL;--> statement-breakpoint
ALTER TABLE `game_skill_catalog` ADD `status_chance` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_skill_catalog` ADD `status_duration` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_skill_catalog` ADD `heal_percent` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_skill_catalog` ADD `profession_required` varchar(20) DEFAULT 'none' NOT NULL;--> statement-breakpoint
ALTER TABLE `game_skill_catalog` ADD `skill_tier` varchar(20) DEFAULT 'basic' NOT NULL;--> statement-breakpoint
ALTER TABLE `game_skill_catalog` ADD `acquire_method` varchar(20) DEFAULT 'levelup' NOT NULL;