CREATE TABLE `game_unified_skill_catalog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(10) NOT NULL,
	`skill_id` varchar(20) NOT NULL DEFAULT '',
	`name` varchar(100) NOT NULL,
	`quest_title` varchar(200),
	`category` varchar(20) NOT NULL,
	`skill_type` varchar(20) NOT NULL DEFAULT 'attack',
	`description` text,
	`wuxing` varchar(10) DEFAULT '無',
	`power_percent` int NOT NULL DEFAULT 100,
	`mp_cost` int NOT NULL DEFAULT 10,
	`cooldown` int NOT NULL DEFAULT 3,
	`max_level` int NOT NULL DEFAULT 10,
	`level_up_bonus` int NOT NULL DEFAULT 10,
	`accuracy_mod` int NOT NULL DEFAULT 100,
	`target_type` varchar(20) NOT NULL DEFAULT 'single',
	`scale_stat` varchar(10) NOT NULL DEFAULT 'atk',
	`usable_by_player` tinyint NOT NULL DEFAULT 1,
	`usable_by_pet` tinyint NOT NULL DEFAULT 1,
	`usable_by_monster` tinyint NOT NULL DEFAULT 1,
	`status_effect_type` varchar(20) NOT NULL DEFAULT 'none',
	`status_effect_chance` int NOT NULL DEFAULT 0,
	`status_effect_duration` int NOT NULL DEFAULT 0,
	`status_effect_value` int NOT NULL DEFAULT 0,
	`hit_count_min` int NOT NULL DEFAULT 1,
	`hit_count_max` int NOT NULL DEFAULT 1,
	`multi_target_hit` tinyint NOT NULL DEFAULT 0,
	`lifesteal_percent` int NOT NULL DEFAULT 0,
	`self_damage_percent` int NOT NULL DEFAULT 0,
	`ignore_def_percent` int NOT NULL DEFAULT 0,
	`is_priority` tinyint NOT NULL DEFAULT 0,
	`heal_type` varchar(20) NOT NULL DEFAULT 'none',
	`hot_duration` int NOT NULL DEFAULT 0,
	`mp_restore_percent` int NOT NULL DEFAULT 0,
	`cleanse_count` int NOT NULL DEFAULT 0,
	`buff_stat` varchar(10) NOT NULL DEFAULT 'none',
	`buff_percent` int NOT NULL DEFAULT 0,
	`buff_duration` int NOT NULL DEFAULT 0,
	`shield_type` varchar(10) NOT NULL DEFAULT 'none',
	`shield_charges` int NOT NULL DEFAULT 0,
	`shield_duration` int NOT NULL DEFAULT 0,
	`shield_absorb_percent` int NOT NULL DEFAULT 0,
	`absorb_type` varchar(10) NOT NULL DEFAULT 'none',
	`absorb_percent` int NOT NULL DEFAULT 0,
	`absorb_duration` int NOT NULL DEFAULT 0,
	`taunt_duration` int NOT NULL DEFAULT 0,
	`is_passive` tinyint NOT NULL DEFAULT 0,
	`passive_type` varchar(20) NOT NULL DEFAULT 'none',
	`passive_trigger_chance` int NOT NULL DEFAULT 0,
	`passive_chance_per_level` int NOT NULL DEFAULT 0,
	`guard_damage_reduction` int NOT NULL DEFAULT 0,
	`low_hp_threshold` int NOT NULL DEFAULT 0,
	`low_hp_boost_percent` int NOT NULL DEFAULT 0,
	`resist_type` varchar(20) NOT NULL DEFAULT 'none',
	`resist_chance_per_level` int NOT NULL DEFAULT 0,
	`has_instant_kill` tinyint NOT NULL DEFAULT 0,
	`instant_kill_chance` int NOT NULL DEFAULT 0,
	`has_steal` tinyint NOT NULL DEFAULT 0,
	`steal_chance` int NOT NULL DEFAULT 0,
	`has_seal_wuxing` tinyint NOT NULL DEFAULT 0,
	`seal_duration` int NOT NULL DEFAULT 0,
	`on_defend_trigger` tinyint NOT NULL DEFAULT 0,
	`defend_heal_percent` int NOT NULL DEFAULT 0,
	`defend_mp_percent` int NOT NULL DEFAULT 0,
	`ai_hp_below` int NOT NULL DEFAULT 0,
	`ai_priority` int NOT NULL DEFAULT 5,
	`ai_target_element` varchar(10) NOT NULL DEFAULT '',
	`rarity` varchar(20) NOT NULL DEFAULT 'rare',
	`learn_cost` json,
	`prerequisites` json,
	`prerequisite_level` int,
	`npc_id` int,
	`additional_effect` json,
	`special_mechanic` json,
	`icon_url` text,
	`sort_order` int NOT NULL DEFAULT 0,
	`is_active` tinyint NOT NULL DEFAULT 1,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `game_unified_skill_catalog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
DROP TABLE `game_monster_skill_catalog`;--> statement-breakpoint
DROP TABLE `game_quest_skill_catalog`;--> statement-breakpoint
DROP TABLE `game_skill_catalog`;--> statement-breakpoint
ALTER TABLE `game_map_nodes` ADD `region` varchar(30) DEFAULT '初界' NOT NULL;--> statement-breakpoint
ALTER TABLE `game_map_nodes` ADD `sub_region` varchar(100);--> statement-breakpoint
ALTER TABLE `game_map_nodes` ADD `description` text;--> statement-breakpoint
ALTER TABLE `game_map_nodes` ADD `level_min` int DEFAULT 1;--> statement-breakpoint
ALTER TABLE `game_map_nodes` ADD `level_max` int DEFAULT 99;--> statement-breakpoint
ALTER TABLE `game_map_nodes` ADD `real_world_name` varchar(200);--> statement-breakpoint
ALTER TABLE `game_map_nodes` ADD `sort_order` int DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `game_npc_catalog` ADD `map_node_id` int;