export type WuXing = "wood" | "fire" | "earth" | "metal" | "water";

export type MapNode = {
  id: string;
  name: string;
  county: string;
  element: WuXing;
  terrain: string; // 地形描述
  description: string; // 場景描述
  dangerLevel: 1 | 2 | 3 | 4 | 5; // 危險等級
  connections: string[]; // 可到達的節點 ID
  travelTime: number; // 移動所需秒數
  monsterLevel: [number, number]; // 怪物等級範圍
  // 地圖座標（用於視覺化，相對於台灣輪廓 0-100）
  x: number;
  y: number;
};

export const MAP_NODES: MapNode[] = [
  // ─── 台北市 ───
  {
    id: "taipei-zhongzheng",
    name: "中正紀念堂廣場",
    county: "台北市",
    element: "earth",
    terrain: "都市廣場",
    description: "宏偉的廣場中央，石板地縫隙間長出了奇異的靈草，偶有土靈精靈出沒。",
    dangerLevel: 1,
    connections: ["taipei-zhongshan", "taipei-daan", "taipei-wanhua"],
    travelTime: 30,
    monsterLevel: [1, 5],
    x: 52, y: 22,
  },
  {
    id: "taipei-zhongshan",
    name: "中山北路商圈",
    county: "台北市",
    element: "metal",
    terrain: "都市商業區",
    description: "繁華的商業街道，金屬氣息濃厚，流浪商人常在此出沒，偶有金靈怪物藏匿於廢棄建物。",
    dangerLevel: 1,
    connections: ["taipei-zhongzheng", "taipei-shilin", "taipei-neihu"],
    travelTime: 30,
    monsterLevel: [1, 6],
    x: 52, y: 20,
  },
  {
    id: "taipei-daan",
    name: "大安森林公園",
    county: "台北市",
    element: "wood",
    terrain: "都市森林",
    description: "城市中的綠洲，古木參天，木靈能量充沛，是初學者採集草藥的好地方。",
    dangerLevel: 1,
    connections: ["taipei-zhongzheng", "taipei-wenshan", "taipei-xinyi"],
    travelTime: 30,
    monsterLevel: [1, 5],
    x: 53, y: 23,
  },
  {
    id: "taipei-xinyi",
    name: "信義區摩天樓群",
    county: "台北市",
    element: "metal",
    terrain: "高樓商業區",
    description: "玻璃帷幕反射著天光，金屬精靈棲居於高樓縫隙，傳說頂樓有稀有的金屬寶箱。",
    dangerLevel: 2,
    connections: ["taipei-daan", "taipei-nangang", "taipei-zhongzheng"],
    travelTime: 30,
    monsterLevel: [3, 8],
    x: 54, y: 22,
  },
  {
    id: "taipei-wanhua",
    name: "萬華龍山寺",
    county: "台北市",
    element: "water",
    terrain: "古廟街區",
    description: "香火繚繞的古廟旁，淡水河的水氣滋養著水靈生物，神秘的占卜師偶爾現身。",
    dangerLevel: 2,
    connections: ["taipei-zhongzheng", "taipei-banqiao"],
    travelTime: 45,
    monsterLevel: [2, 7],
    x: 50, y: 23,
  },
  {
    id: "taipei-shilin",
    name: "士林夜市迷宮",
    county: "台北市",
    element: "fire",
    terrain: "夜市街區",
    description: "熱鬧的夜市中，爐火的氣息吸引了火靈生物，流浪商人在此販售稀有食材。",
    dangerLevel: 2,
    connections: ["taipei-zhongshan", "taipei-beitou"],
    travelTime: 40,
    monsterLevel: [2, 7],
    x: 51, y: 19,
  },
  {
    id: "taipei-beitou",
    name: "北投溫泉谷",
    county: "台北市",
    element: "fire",
    terrain: "溫泉地熱區",
    description: "硫磺蒸氣瀰漫，地熱能量豐沛，火屬性怪物在此特別強大，但掉落的礦石也更珍貴。",
    dangerLevel: 3,
    connections: ["taipei-shilin", "yangmingshan-peak"],
    travelTime: 60,
    monsterLevel: [5, 12],
    x: 50, y: 17,
  },
  {
    id: "taipei-wenshan",
    name: "木柵貓空茶山",
    county: "台北市",
    element: "wood",
    terrain: "山地茶園",
    description: "翠綠的茶園延伸至山腰，木靈氣息濃厚，採茶精靈與山獸在此和平共存。",
    dangerLevel: 2,
    connections: ["taipei-daan", "xindian-valley"],
    travelTime: 60,
    monsterLevel: [3, 8],
    x: 53, y: 25,
  },
  {
    id: "taipei-neihu",
    name: "內湖科技園區廢墟",
    county: "台北市",
    element: "metal",
    terrain: "廢棄科技園區",
    description: "廢棄的科技廠房中，金屬廢料孕育出機械怪物，偶有稀有的電子零件散落其中。",
    dangerLevel: 3,
    connections: ["taipei-zhongshan", "taipei-nangang"],
    travelTime: 40,
    monsterLevel: [5, 12],
    x: 55, y: 20,
  },
  {
    id: "taipei-nangang",
    name: "南港山脈入口",
    county: "台北市",
    element: "wood",
    terrain: "山脈入口",
    description: "通往山脈的入口，古老的石碑記載著傳說中的寶藏，但也警告著深山中的危險。",
    dangerLevel: 3,
    connections: ["taipei-xinyi", "taipei-neihu", "keelung-city"],
    travelTime: 60,
    monsterLevel: [5, 12],
    x: 56, y: 21,
  },

  // ─── 陽明山 ───
  {
    id: "yangmingshan-peak",
    name: "陽明山主峰",
    county: "台北市",
    element: "fire",
    terrain: "火山高地",
    description: "休眠火山的頂峰，硫磺噴氣孔周圍聚集著強力的火屬性精英怪，傳說山頂有火靈寶珠。",
    dangerLevel: 4,
    connections: ["taipei-beitou", "danshui-coast"],
    travelTime: 90,
    monsterLevel: [10, 20],
    x: 49, y: 16,
  },

  // ─── 新北市 ───
  {
    id: "taipei-banqiao",
    name: "板橋府中商圈",
    county: "新北市",
    element: "earth",
    terrain: "都市平原",
    description: "新北市的行政中心，土靈能量穩定，是補給物資的好地點，偶有商人在廣場擺攤。",
    dangerLevel: 1,
    connections: ["taipei-wanhua", "xinzhuang-plain", "zhonghe-hills"],
    travelTime: 45,
    monsterLevel: [1, 5],
    x: 49, y: 24,
  },
  {
    id: "xinzhuang-plain",
    name: "新莊平原",
    county: "新北市",
    element: "earth",
    terrain: "農業平原",
    description: "廣闊的農業平原，土靈生物在田間嬉戲，農夫偶爾會委託旅人驅除害蟲。",
    dangerLevel: 1,
    connections: ["taipei-banqiao", "sanchong-riverside"],
    travelTime: 40,
    monsterLevel: [1, 5],
    x: 48, y: 22,
  },
  {
    id: "sanchong-riverside",
    name: "三重淡水河畔",
    county: "新北市",
    element: "water",
    terrain: "河岸濕地",
    description: "淡水河的支流在此交匯，水靈生物聚集，漁夫傳說河底有古老的水晶礦脈。",
    dangerLevel: 2,
    connections: ["xinzhuang-plain", "danshui-coast"],
    travelTime: 50,
    monsterLevel: [2, 8],
    x: 49, y: 21,
  },
  {
    id: "danshui-coast",
    name: "淡水老街海岸",
    county: "新北市",
    element: "water",
    terrain: "海岸古鎮",
    description: "夕陽映照的老街旁，海浪拍打著礁石，水靈怪物在潮間帶出沒，偶有神秘的海上商船靠岸。",
    dangerLevel: 2,
    connections: ["sanchong-riverside", "yangmingshan-peak", "jiufen-hills"],
    travelTime: 60,
    monsterLevel: [3, 9],
    x: 47, y: 18,
  },
  {
    id: "zhonghe-hills",
    name: "中和圓通寺山丘",
    county: "新北市",
    element: "wood",
    terrain: "丘陵寺廟",
    description: "古寺掩映在綠樹之間，木靈能量充沛，僧侶傳授採藥技巧，偶有木靈精英守護寺廟。",
    dangerLevel: 2,
    connections: ["taipei-banqiao", "xindian-valley"],
    travelTime: 50,
    monsterLevel: [2, 8],
    x: 50, y: 26,
  },
  {
    id: "xindian-valley",
    name: "新店碧潭峽谷",
    county: "新北市",
    element: "water",
    terrain: "峽谷水潭",
    description: "碧綠的潭水倒映著峭壁，水靈能量極強，傳說潭底住著古老的水龍，守護著珍貴的水晶。",
    dangerLevel: 3,
    connections: ["zhonghe-hills", "taipei-wenshan", "wulai-forest"],
    travelTime: 60,
    monsterLevel: [5, 12],
    x: 52, y: 27,
  },
  {
    id: "wulai-forest",
    name: "烏來原始森林",
    county: "新北市",
    element: "wood",
    terrain: "原始森林",
    description: "未開發的原始森林，木靈能量達到頂峰，強力的木屬性 Boss 在此盤踞，但寶藏也最為豐富。",
    dangerLevel: 4,
    connections: ["xindian-valley"],
    travelTime: 90,
    monsterLevel: [12, 22],
    x: 51, y: 29,
  },
  {
    id: "jiufen-hills",
    name: "九份山城礦區",
    county: "新北市",
    element: "metal",
    terrain: "山城礦區",
    description: "廢棄的金礦坑道蜿蜒入山，金屬精靈守護著殘存的礦脈，燈籠搖曳間透著詭異的光芒。",
    dangerLevel: 3,
    connections: ["danshui-coast", "keelung-city", "jinguashi-mine"],
    travelTime: 70,
    monsterLevel: [6, 14],
    x: 55, y: 18,
  },
  {
    id: "jinguashi-mine",
    name: "金瓜石黃金礦坑",
    county: "新北市",
    element: "metal",
    terrain: "黃金礦坑",
    description: "昔日的黃金礦坑，金屬能量極為濃厚，金屬 Boss 在此鎮守，傳說最深處藏有傳說級裝備。",
    dangerLevel: 4,
    connections: ["jiufen-hills", "northeast-coast"],
    travelTime: 80,
    monsterLevel: [12, 22],
    x: 57, y: 17,
  },

  // ─── 基隆市 ───
  {
    id: "keelung-city",
    name: "基隆港口",
    county: "基隆市",
    element: "water",
    terrain: "港口城市",
    description: "霧氣瀰漫的港口，水靈生物在碼頭附近遊蕩，神秘的船長偶爾帶來異地的稀有物品。",
    dangerLevel: 2,
    connections: ["taipei-nangang", "jiufen-hills", "northeast-coast"],
    travelTime: 60,
    monsterLevel: [3, 9],
    x: 56, y: 16,
  },
  {
    id: "northeast-coast",
    name: "東北角海岸",
    county: "基隆市",
    element: "water",
    terrain: "岩礁海岸",
    description: "奇特的岩礁地形，海浪侵蝕出天然洞穴，水靈精英在此棲居，退潮時可找到珍貴的海洋礦石。",
    dangerLevel: 3,
    connections: ["keelung-city", "jinguashi-mine", "yilan-coast"],
    travelTime: 80,
    monsterLevel: [6, 14],
    x: 59, y: 16,
  },

  // ─── 桃園市 ───
  {
    id: "taoyuan-airport",
    name: "桃園機場平原",
    county: "桃園市",
    element: "earth",
    terrain: "廣闊平原",
    description: "機場周圍的廣闊平原，土靈能量穩定，是往來各地的重要中繼點，商人頻繁出沒。",
    dangerLevel: 1,
    connections: ["taipei-banqiao", "taoyuan-city", "zhongli-plain"],
    travelTime: 60,
    monsterLevel: [1, 6],
    x: 45, y: 24,
  },
  {
    id: "taoyuan-city",
    name: "桃園市中心",
    county: "桃園市",
    element: "earth",
    terrain: "都市平原",
    description: "桃園的商業中心，土靈商人在此設攤，各種基礎物資應有盡有，是補給的最佳地點。",
    dangerLevel: 1,
    connections: ["taoyuan-airport", "zhongli-plain", "daxi-valley"],
    travelTime: 40,
    monsterLevel: [1, 5],
    x: 44, y: 25,
  },
  {
    id: "zhongli-plain",
    name: "中壢農業平原",
    county: "桃園市",
    element: "earth",
    terrain: "農業平原",
    description: "肥沃的農業平原，土靈能量豐沛，農業精靈在此耕作，偶有土屬性怪物破壞農田。",
    dangerLevel: 1,
    connections: ["taoyuan-airport", "taoyuan-city", "hsinchu-city"],
    travelTime: 50,
    monsterLevel: [1, 6],
    x: 43, y: 27,
  },
  {
    id: "daxi-valley",
    name: "大溪老街河谷",
    county: "桃園市",
    element: "water",
    terrain: "河谷古鎮",
    description: "大漢溪蜿蜒流過的古鎮，水靈能量充沛，豆腐商人傳說掌握著水靈召喚的秘法。",
    dangerLevel: 2,
    connections: ["taoyuan-city", "fuxing-mountain"],
    travelTime: 60,
    monsterLevel: [3, 9],
    x: 43, y: 26,
  },
  {
    id: "fuxing-mountain",
    name: "復興山地部落",
    county: "桃園市",
    element: "wood",
    terrain: "山地部落",
    description: "原住民部落深藏於山中，木靈薩滿守護著古老的森林，強力的木屬性怪物在此盤踞。",
    dangerLevel: 4,
    connections: ["daxi-valley", "wuling-peak"],
    travelTime: 120,
    monsterLevel: [12, 22],
    x: 42, y: 28,
  },

  // ─── 新竹縣市 ───
  {
    id: "hsinchu-city",
    name: "新竹科學城",
    county: "新竹市",
    element: "metal",
    terrain: "科技城市",
    description: "科技重鎮，金屬能量在此凝聚，機械怪物在廢棄廠房中出沒，偶有稀有的電子元件掉落。",
    dangerLevel: 2,
    connections: ["zhongli-plain", "hsinchu-coast", "zhudong-hills"],
    travelTime: 60,
    monsterLevel: [3, 9],
    x: 41, y: 30,
  },
  {
    id: "hsinchu-coast",
    name: "新竹海岸風場",
    county: "新竹市",
    element: "metal",
    terrain: "海岸風場",
    description: "強勁的海風帶動著風力發電機，金屬能量在此達到高峰，風靈怪物在此肆虐。",
    dangerLevel: 2,
    connections: ["hsinchu-city", "miaoli-coast"],
    travelTime: 50,
    monsterLevel: [3, 9],
    x: 39, y: 30,
  },
  {
    id: "zhudong-hills",
    name: "竹東丘陵",
    county: "新竹縣",
    element: "wood",
    terrain: "丘陵地帶",
    description: "起伏的丘陵間，木靈能量充沛，客家聚落的老農傳說山中有木靈守護神。",
    dangerLevel: 2,
    connections: ["hsinchu-city", "wufeng-mountain"],
    travelTime: 60,
    monsterLevel: [3, 9],
    x: 42, y: 31,
  },
  {
    id: "wufeng-mountain",
    name: "五峰山地",
    county: "新竹縣",
    element: "wood",
    terrain: "高山森林",
    description: "五峰連綿的高山，原始森林中木靈精英盤踞，傳說山頂有千年木靈樹，能賦予強大的木屬性力量。",
    dangerLevel: 4,
    connections: ["zhudong-hills", "wuling-peak"],
    travelTime: 120,
    monsterLevel: [12, 22],
    x: 41, y: 33,
  },

  // ─── 苗栗縣 ───
  {
    id: "miaoli-coast",
    name: "苗栗海岸",
    county: "苗栗縣",
    element: "water",
    terrain: "海岸平原",
    description: "平靜的海岸線，水靈生物在礁石間嬉戲，漁村老人傳說深海中有古老的水靈神殿。",
    dangerLevel: 2,
    connections: ["hsinchu-coast", "miaoli-city"],
    travelTime: 60,
    monsterLevel: [3, 9],
    x: 38, y: 33,
  },
  {
    id: "miaoli-city",
    name: "苗栗市丘陵",
    county: "苗栗縣",
    element: "earth",
    terrain: "丘陵城市",
    description: "丘陵起伏的苗栗市，土靈能量穩定，客家文化保存完好，偶有土靈商人出沒。",
    dangerLevel: 2,
    connections: ["miaoli-coast", "sanyi-mountain", "taichung-north"],
    travelTime: 60,
    monsterLevel: [3, 9],
    x: 40, y: 34,
  },
  {
    id: "sanyi-mountain",
    name: "三義木雕山城",
    county: "苗栗縣",
    element: "wood",
    terrain: "山城木雕區",
    description: "木雕藝術之鄉，木靈能量在此昇華為藝術，木靈精英守護著百年神木，掉落珍貴的木靈精華。",
    dangerLevel: 3,
    connections: ["miaoli-city", "wuling-peak"],
    travelTime: 80,
    monsterLevel: [6, 14],
    x: 40, y: 36,
  },

  // ─── 台中市 ───
  {
    id: "taichung-north",
    name: "台中北區商圈",
    county: "台中市",
    element: "earth",
    terrain: "都市商業區",
    description: "台中的繁華商圈，土靈商人雲集，各種物資應有盡有，是中部最重要的補給站。",
    dangerLevel: 1,
    connections: ["miaoli-city", "taichung-center", "taichung-coast"],
    travelTime: 60,
    monsterLevel: [1, 6],
    x: 40, y: 38,
  },
  {
    id: "taichung-center",
    name: "台中市中心公園",
    county: "台中市",
    element: "wood",
    terrain: "都市公園",
    description: "綠意盎然的都市公園，木靈能量充沛，是中部旅人休息補給的好地方。",
    dangerLevel: 1,
    connections: ["taichung-north", "taichung-east", "nantou-city"],
    travelTime: 30,
    monsterLevel: [1, 5],
    x: 41, y: 39,
  },
  {
    id: "taichung-coast",
    name: "台中港海岸",
    county: "台中市",
    element: "water",
    terrain: "工業港口",
    description: "工業港口旁，水靈生物在污染的海水中變異，掉落特殊的變異素材，偶有走私商人出沒。",
    dangerLevel: 3,
    connections: ["taichung-north", "changhua-plain"],
    travelTime: 60,
    monsterLevel: [5, 12],
    x: 38, y: 39,
  },
  {
    id: "taichung-east",
    name: "台中東山丘陵",
    county: "台中市",
    element: "wood",
    terrain: "丘陵茶園",
    description: "東山的茶園延伸至山腰，木靈能量充沛，採茶精靈與山獸在此和平共存。",
    dangerLevel: 2,
    connections: ["taichung-center", "wuling-peak"],
    travelTime: 80,
    monsterLevel: [3, 9],
    x: 43, y: 38,
  },

  // ─── 武陵高山 ───
  {
    id: "wuling-peak",
    name: "武陵四秀高山",
    county: "台中市",
    element: "wood",
    terrain: "高山峻嶺",
    description: "台灣最高峻的山脈之一，木靈能量達到極致，傳說中的木靈神獸在此棲居，挑戰者九死一生。",
    dangerLevel: 5,
    connections: ["fuxing-mountain", "wufeng-mountain", "sanyi-mountain", "taichung-east"],
    travelTime: 180,
    monsterLevel: [18, 30],
    x: 43, y: 33,
  },

  // ─── 彰化縣 ───
  {
    id: "changhua-plain",
    name: "彰化大平原",
    county: "彰化縣",
    element: "earth",
    terrain: "農業大平原",
    description: "台灣最大的農業平原，土靈能量極為豐沛，土靈農夫精靈在此耕作，偶有土靈 Boss 守護農田。",
    dangerLevel: 2,
    connections: ["taichung-coast", "changhua-city", "yunlin-plain"],
    travelTime: 60,
    monsterLevel: [2, 8],
    x: 39, y: 42,
  },
  {
    id: "changhua-city",
    name: "彰化市八卦山",
    county: "彰化縣",
    element: "earth",
    terrain: "山丘城市",
    description: "八卦山大佛俯瞰著彰化平原，土靈能量在此凝聚，山腰的蝴蝶谷中有稀有的蝶靈出沒。",
    dangerLevel: 2,
    connections: ["changhua-plain", "nantou-city"],
    travelTime: 50,
    monsterLevel: [2, 8],
    x: 40, y: 43,
  },

  // ─── 南投縣 ───
  {
    id: "nantou-city",
    name: "南投市草屯",
    county: "南投縣",
    element: "earth",
    terrain: "盆地城市",
    description: "南投的門戶，土靈能量穩定，是進入中部山區的重要補給站，商人在此設立固定攤位。",
    dangerLevel: 1,
    connections: ["taichung-center", "changhua-city", "puli-basin"],
    travelTime: 60,
    monsterLevel: [1, 6],
    x: 42, y: 42,
  },
  {
    id: "puli-basin",
    name: "埔里盆地",
    county: "南投縣",
    element: "earth",
    terrain: "山中盆地",
    description: "台灣地理中心附近的盆地，土靈能量在此達到平衡，傳說此地是五行能量的交匯點。",
    dangerLevel: 2,
    connections: ["nantou-city", "sunmoon-lake", "hehuanshan-peak"],
    travelTime: 80,
    monsterLevel: [3, 9],
    x: 43, y: 44,
  },
  {
    id: "sunmoon-lake",
    name: "日月潭靈湖",
    county: "南投縣",
    element: "water",
    terrain: "高山湖泊",
    description: "台灣最美的高山湖泊，水靈能量極為純淨，水靈精英在此守護，傳說湖底有古老的水靈神殿。",
    dangerLevel: 3,
    connections: ["puli-basin", "alishan-forest"],
    travelTime: 90,
    monsterLevel: [6, 14],
    x: 42, y: 46,
  },
  {
    id: "hehuanshan-peak",
    name: "合歡山雪地",
    county: "南投縣",
    element: "water",
    terrain: "高山雪地",
    description: "冬日積雪的合歡山，水靈能量在低溫中凝固成冰晶，冰靈怪物在此橫行，寶藏凍結於冰雪之中。",
    dangerLevel: 5,
    connections: ["puli-basin"],
    travelTime: 180,
    monsterLevel: [18, 30],
    x: 44, y: 42,
  },

  // ─── 雲林縣 ───
  {
    id: "yunlin-plain",
    name: "雲林農業平原",
    county: "雲林縣",
    element: "earth",
    terrain: "農業平原",
    description: "台灣農業重鎮，土靈能量豐沛，農業精靈在此耕作，偶有土靈怪物破壞農田需要驅除。",
    dangerLevel: 1,
    connections: ["changhua-plain", "yunlin-coast", "chiayi-plain"],
    travelTime: 60,
    monsterLevel: [1, 6],
    x: 38, y: 46,
  },
  {
    id: "yunlin-coast",
    name: "雲林離島工業區",
    county: "雲林縣",
    element: "fire",
    terrain: "工業海岸",
    description: "石化工業區的煙囪日夜噴火，火靈能量在此異常濃厚，變異的火靈怪物在廠區出沒。",
    dangerLevel: 3,
    connections: ["yunlin-plain", "chiayi-coast"],
    travelTime: 70,
    monsterLevel: [5, 12],
    x: 36, y: 46,
  },

  // ─── 嘉義縣市 ───
  {
    id: "chiayi-plain",
    name: "嘉義市平原",
    county: "嘉義市",
    element: "earth",
    terrain: "平原城市",
    description: "嘉義的商業中心，土靈能量穩定，是南部重要的補給站，火雞肉飯商人傳說掌握著土靈秘法。",
    dangerLevel: 1,
    connections: ["yunlin-plain", "chiayi-coast", "alishan-forest"],
    travelTime: 60,
    monsterLevel: [1, 6],
    x: 39, y: 49,
  },
  {
    id: "chiayi-coast",
    name: "嘉義布袋海岸",
    county: "嘉義縣",
    element: "water",
    terrain: "鹽田海岸",
    description: "廣闊的鹽田旁，水靈能量在鹽分中結晶，鹽靈怪物在此出沒，掉落珍貴的鹽晶礦石。",
    dangerLevel: 2,
    connections: ["yunlin-coast", "chiayi-plain", "tainan-coast"],
    travelTime: 60,
    monsterLevel: [2, 8],
    x: 37, y: 50,
  },
  {
    id: "alishan-forest",
    name: "阿里山神木林",
    county: "嘉義縣",
    element: "wood",
    terrain: "高山神木林",
    description: "千年神木聳立入雲，木靈能量在此達到頂峰，木靈 Boss 神木守護者在此鎮守，傳說神木中藏有傳說技能書。",
    dangerLevel: 5,
    connections: ["chiayi-plain", "sunmoon-lake", "yushan-peak"],
    travelTime: 180,
    monsterLevel: [18, 30],
    x: 41, y: 50,
  },

  // ─── 玉山 ───
  {
    id: "yushan-peak",
    name: "玉山主峰",
    county: "南投縣",
    element: "metal",
    terrain: "最高峰",
    description: "台灣最高峰，金屬能量在此凝聚為純金，傳說山頂有天命級裝備，但守護它的金靈神獸幾乎無法被擊敗。",
    dangerLevel: 5,
    connections: ["alishan-forest", "hehuanshan-peak"],
    travelTime: 240,
    monsterLevel: [25, 40],
    x: 43, y: 49,
  },

  // ─── 台南市 ───
  {
    id: "tainan-coast",
    name: "台南安平古堡海岸",
    county: "台南市",
    element: "water",
    terrain: "古堡海岸",
    description: "荷蘭時代的古堡遺址旁，水靈能量與歷史氣息交融，古老的水靈在此徘徊，掉落歷史文物。",
    dangerLevel: 2,
    connections: ["chiayi-coast", "tainan-city", "kaohsiung-coast"],
    travelTime: 60,
    monsterLevel: [2, 8],
    x: 38, y: 54,
  },
  {
    id: "tainan-city",
    name: "台南市古都",
    county: "台南市",
    element: "fire",
    terrain: "古都城市",
    description: "台灣最古老的城市，火靈能量在古廟香火中燃燒，廟宇商人販售稀有的符咒與靈藥。",
    dangerLevel: 2,
    connections: ["tainan-coast", "tainan-mountain", "kaohsiung-city"],
    travelTime: 40,
    monsterLevel: [2, 8],
    x: 39, y: 55,
  },
  {
    id: "tainan-mountain",
    name: "台南關廟山區",
    county: "台南市",
    element: "wood",
    terrain: "山地農業區",
    description: "鳳梨種植的山區，木靈能量充沛，農業精靈在此耕作，偶有木靈怪物破壞農田。",
    dangerLevel: 2,
    connections: ["tainan-city", "kaohsiung-mountain"],
    travelTime: 60,
    monsterLevel: [2, 8],
    x: 40, y: 57,
  },

  // ─── 高雄市 ───
  {
    id: "kaohsiung-coast",
    name: "高雄港口工業區",
    county: "高雄市",
    element: "metal",
    terrain: "工業港口",
    description: "台灣最大的工業港口，金屬能量極為濃厚，鋼鐵怪物在廠區出沒，偶有稀有的金屬礦石掉落。",
    dangerLevel: 3,
    connections: ["tainan-coast", "kaohsiung-city", "pingtung-plain"],
    travelTime: 60,
    monsterLevel: [5, 12],
    x: 39, y: 58,
  },
  {
    id: "kaohsiung-city",
    name: "高雄市中心",
    county: "高雄市",
    element: "fire",
    terrain: "都市中心",
    description: "南台灣最大城市，火靈能量在都市熱氣中燃燒，是南部最重要的補給站，商人雲集。",
    dangerLevel: 1,
    connections: ["tainan-city", "kaohsiung-coast", "kaohsiung-mountain"],
    travelTime: 40,
    monsterLevel: [1, 6],
    x: 40, y: 59,
  },
  {
    id: "kaohsiung-mountain",
    name: "高雄茂林峽谷",
    county: "高雄市",
    element: "water",
    terrain: "峽谷溪流",
    description: "茂林峽谷中，溪流湍急，水靈能量充沛，紫蝶幻化的蝶靈在此出沒，掉落珍貴的蝶翼素材。",
    dangerLevel: 3,
    connections: ["kaohsiung-city", "tainan-mountain", "pingtung-mountain"],
    travelTime: 80,
    monsterLevel: [5, 12],
    x: 41, y: 61,
  },

  // ─── 屏東縣 ───
  {
    id: "pingtung-plain",
    name: "屏東平原",
    county: "屏東縣",
    element: "earth",
    terrain: "農業平原",
    description: "台灣最南端的農業平原，土靈能量豐沛，熱帶農業精靈在此耕作，偶有土靈怪物出沒。",
    dangerLevel: 1,
    connections: ["kaohsiung-coast", "pingtung-city", "hengchun-peninsula"],
    travelTime: 60,
    monsterLevel: [1, 6],
    x: 41, y: 62,
  },
  {
    id: "pingtung-city",
    name: "屏東市",
    county: "屏東縣",
    element: "fire",
    terrain: "南方城市",
    description: "南台灣的熱帶城市，火靈能量在烈日下燃燒，熱帶商人販售特殊的南方靈藥。",
    dangerLevel: 1,
    connections: ["pingtung-plain", "pingtung-mountain"],
    travelTime: 40,
    monsterLevel: [1, 6],
    x: 42, y: 63,
  },
  {
    id: "pingtung-mountain",
    name: "屏東霧台山地",
    county: "屏東縣",
    element: "wood",
    terrain: "山地部落",
    description: "魯凱族的傳統領地，木靈薩滿守護著古老的山林，強力的木靈精英在此盤踞。",
    dangerLevel: 4,
    connections: ["pingtung-city", "kaohsiung-mountain"],
    travelTime: 120,
    monsterLevel: [12, 22],
    x: 43, y: 64,
  },
  {
    id: "hengchun-peninsula",
    name: "恆春半島墾丁",
    county: "屏東縣",
    element: "water",
    terrain: "熱帶海岸",
    description: "台灣最南端的熱帶海岸，水靈能量在珊瑚礁中結晶，海洋 Boss 在此鎮守，傳說珊瑚礁底有傳說寶藏。",
    dangerLevel: 4,
    connections: ["pingtung-plain", "taitung-coast"],
    travelTime: 120,
    monsterLevel: [12, 22],
    x: 42, y: 67,
  },

  // ─── 宜蘭縣 ───
  {
    id: "yilan-coast",
    name: "宜蘭海岸平原",
    county: "宜蘭縣",
    element: "water",
    terrain: "海岸平原",
    description: "雪山山脈與太平洋之間的平原，水靈能量充沛，漁村商人販售珍貴的海洋素材。",
    dangerLevel: 2,
    connections: ["northeast-coast", "yilan-city", "taroko-gorge"],
    travelTime: 80,
    monsterLevel: [2, 8],
    x: 60, y: 20,
  },
  {
    id: "yilan-city",
    name: "宜蘭市",
    county: "宜蘭縣",
    element: "water",
    terrain: "盆地城市",
    description: "雨都宜蘭，水靈能量在雨水中不斷補充，是東部重要的補給站，商人在此販售水靈藥水。",
    dangerLevel: 1,
    connections: ["yilan-coast", "jiaoxi-hotspring"],
    travelTime: 40,
    monsterLevel: [1, 6],
    x: 61, y: 22,
  },
  {
    id: "jiaoxi-hotspring",
    name: "礁溪溫泉谷",
    county: "宜蘭縣",
    element: "fire",
    terrain: "溫泉地熱",
    description: "礁溪的溫泉從地底湧出，火靈能量在熱水中凝聚，火靈怪物在此特別活躍。",
    dangerLevel: 2,
    connections: ["yilan-city", "taroko-gorge"],
    travelTime: 60,
    monsterLevel: [3, 9],
    x: 60, y: 24,
  },

  // ─── 花蓮縣 ───
  {
    id: "taroko-gorge",
    name: "太魯閣峽谷",
    county: "花蓮縣",
    element: "metal",
    terrain: "大理石峽谷",
    description: "世界級的大理石峽谷，金屬能量在岩壁中凝聚，金屬精英怪物在峭壁上棲居，傳說峽谷深處有天命裝備。",
    dangerLevel: 4,
    connections: ["yilan-coast", "jiaoxi-hotspring", "hualien-city"],
    travelTime: 120,
    monsterLevel: [12, 22],
    x: 61, y: 27,
  },
  {
    id: "hualien-city",
    name: "花蓮市",
    county: "花蓮縣",
    element: "earth",
    terrain: "東部城市",
    description: "花東縱谷的北端，土靈能量穩定，是東部最重要的補給站，玉石商人在此販售珍貴的玉靈礦石。",
    dangerLevel: 1,
    connections: ["taroko-gorge", "hualien-valley"],
    travelTime: 60,
    monsterLevel: [1, 6],
    x: 62, y: 30,
  },
  {
    id: "hualien-valley",
    name: "花東縱谷",
    county: "花蓮縣",
    element: "earth",
    terrain: "縱谷平原",
    description: "中央山脈與海岸山脈之間的縱谷，土靈能量豐沛，農業精靈在此耕作，偶有土靈精英出沒。",
    dangerLevel: 2,
    connections: ["hualien-city", "taitung-city"],
    travelTime: 90,
    monsterLevel: [3, 9],
    x: 62, y: 35,
  },

  // ─── 台東縣 ───
  {
    id: "taitung-city",
    name: "台東市",
    county: "台東縣",
    element: "earth",
    terrain: "東部城市",
    description: "台東的都市中心，土靈能量穩定，是東部南段的重要補給站，原住民商人販售特殊的山林素材。",
    dangerLevel: 1,
    connections: ["hualien-valley", "taitung-coast", "taitung-mountain"],
    travelTime: 60,
    monsterLevel: [1, 6],
    x: 62, y: 42,
  },
  {
    id: "taitung-coast",
    name: "台東海岸",
    county: "台東縣",
    element: "water",
    terrain: "太平洋海岸",
    description: "面向太平洋的壯闊海岸，水靈能量在深海中凝聚，海洋怪物在此出沒，偶有深海寶物被海浪沖上岸。",
    dangerLevel: 3,
    connections: ["taitung-city", "hengchun-peninsula", "lyudao-island"],
    travelTime: 80,
    monsterLevel: [5, 12],
    x: 63, y: 44,
  },
  {
    id: "taitung-mountain",
    name: "台東中央山脈",
    county: "台東縣",
    element: "wood",
    terrain: "高山森林",
    description: "中央山脈的南段，原始森林中木靈精英盤踞，卑南族薩滿守護著古老的山林秘密。",
    dangerLevel: 4,
    connections: ["taitung-city"],
    travelTime: 120,
    monsterLevel: [12, 22],
    x: 61, y: 46,
  },
  {
    id: "lyudao-island",
    name: "綠島火山礁岩",
    county: "台東縣",
    element: "fire",
    terrain: "火山島嶼",
    description: "海底火山形成的小島，火靈能量在礁岩中燃燒，火靈 Boss 在此鎮守，傳說島上有稀有的火靈寶珠。",
    dangerLevel: 4,
    connections: ["taitung-coast"],
    travelTime: 150,
    monsterLevel: [12, 22],
    x: 66, y: 46,
  },

  // ─── 澎湖縣 ───
  {
    id: "penghu-islands",
    name: "澎湖玄武岩群島",
    county: "澎湖縣",
    element: "water",
    terrain: "玄武岩島嶼",
    description: "由玄武岩構成的群島，水靈能量在海風中凝聚，海洋精英怪物在礁岩間出沒，傳說有隱藏的海底神殿。",
    dangerLevel: 4,
    connections: ["chiayi-coast"],
    travelTime: 180,
    monsterLevel: [12, 22],
    x: 30, y: 52,
  },
];

// 依 ID 快速查找
export const NODE_MAP: Record<string, MapNode> = Object.fromEntries(
  MAP_NODES.map((n) => [n.id, n])
);

// 五行相剋關係
export const WUXING_OVERCOME: Record<WuXing, WuXing> = {
  wood: "earth",  // 木剋土
  earth: "water", // 土剋水
  water: "fire",  // 水剋火
  fire: "metal",  // 火剋金
  metal: "wood",  // 金剋木
};

// 五行相生關係
export const WUXING_GENERATE: Record<WuXing, WuXing> = {
  wood: "fire",   // 木生火
  fire: "earth",  // 火生土
  earth: "metal", // 土生金
  metal: "water", // 金生水
  water: "wood",  // 水生木
};

// 計算五行加成倍率
export function calcWuxingMultiplier(attacker: WuXing, defender: WuXing): number {
  if (WUXING_OVERCOME[attacker] === defender) return 1.5; // 相剋：傷害 +50%
  if (WUXING_OVERCOME[defender] === attacker) return 0.7; // 被剋：傷害 -30%
  if (WUXING_GENERATE[attacker] === defender) return 1.2; // 相生：傷害 +20%
  return 1.0;
}

// 今日流日元素（根據農曆天干）
export function getDailyElement(stem: string): WuXing {
  const stemMap: Record<string, WuXing> = {
    甲: "wood", 乙: "wood",
    丙: "fire", 丁: "fire",
    戊: "earth", 己: "earth",
    庚: "metal", 辛: "metal",
    壬: "water", 癸: "water",
  };
  return stemMap[stem] ?? "earth";
}
