import type { WuXing } from "./types";

export type MapNode = {
  id: string;
  name: string;
  county: string;
  element: WuXing;
  terrain: string;
  description: string;
  /** 真實景點/地標名稱（可多個） */
  landmarks: string[];
  dangerLevel: 1 | 2 | 3 | 4 | 5;
  connections: string[];
  travelTime: number;
  monsterLevel: [number, number];
  x: number; // 0-100，相對台灣輪廓
  y: number; // 0-100，相對台灣輪廓
};

export const MAP_NODES: MapNode[] = [

  // ════════════════════════════════════════
  // 台北市（16 節點）
  // ════════════════════════════════════════
  {
    id: "tp-zhongzheng",
    name: "中正廣場",
    county: "台北市",
    element: "earth",
    terrain: "都市廣場",
    description: "宏偉廣場中央，石板縫隙間長出靈草，土靈精靈在石柱間嬉戲。",
    landmarks: ["中正紀念堂", "自由廣場", "國家戲劇院", "國家音樂廳"],
    dangerLevel: 1,
    connections: ["tp-zhongshan", "tp-daan", "tp-wanhua", "tp-xinyi"],
    travelTime: 30,
    monsterLevel: [1, 5],
    x: 47, y: 19,
  },
  {
    id: "tp-zhongshan",
    name: "中山商圈",
    county: "台北市",
    element: "metal",
    terrain: "都市商業區",
    description: "繁華商業街道，金屬氣息濃厚，流浪商人常在此出沒。",
    landmarks: ["中山北路", "林森北路", "晴光市場", "中山捷運站"],
    dangerLevel: 1,
    connections: ["tp-zhongzheng", "tp-shilin", "tp-neihu", "tp-datong"],
    travelTime: 30,
    monsterLevel: [1, 6],
    x: 47, y: 17,
  },
  {
    id: "tp-daan",
    name: "大安森林",
    county: "台北市",
    element: "wood",
    terrain: "都市森林",
    description: "城市中的綠洲，古木參天，木靈能量充沛，是採集草藥的好地方。",
    landmarks: ["大安森林公園", "台灣大學", "師範大學", "公館商圈"],
    dangerLevel: 1,
    connections: ["tp-zhongzheng", "tp-wenshan", "tp-xinyi", "tp-zhonghe"],
    travelTime: 30,
    monsterLevel: [1, 5],
    x: 48, y: 21,
  },
  {
    id: "tp-xinyi",
    name: "信義金融區",
    county: "台北市",
    element: "metal",
    terrain: "現代商業中心",
    description: "高樓林立的金融核心，金靈能量在玻璃帷幕間流動，偶有金屬怪物藏匿。",
    landmarks: ["台北101", "信義商圈", "象山步道", "四四南村"],
    dangerLevel: 2,
    connections: ["tp-zhongzheng", "tp-daan", "tp-nangang"],
    travelTime: 30,
    monsterLevel: [3, 8],
    x: 50, y: 21,
  },
  {
    id: "tp-shilin",
    name: "士林夜市",
    county: "台北市",
    element: "fire",
    terrain: "夜市商圈",
    description: "火光映照的夜市，熱鬧喧囂中藏有火靈的蹤跡，食物香氣吸引各路旅人。",
    landmarks: ["士林夜市", "故宮博物院", "天母商圈", "劍潭公園"],
    dangerLevel: 1,
    connections: ["tp-zhongshan", "tp-beitou", "tp-neihu"],
    travelTime: 35,
    monsterLevel: [1, 6],
    x: 46, y: 14,
  },
  {
    id: "tp-beitou",
    name: "北投溫泉",
    county: "台北市",
    element: "water",
    terrain: "溫泉山區",
    description: "硫磺氣息瀰漫的溫泉鄉，水靈能量在熱泉中湧動，山中藏有古老的水靈獸。",
    landmarks: ["北投溫泉博物館", "地熱谷", "北投公園", "陽明山國家公園"],
    dangerLevel: 2,
    connections: ["tp-shilin", "tp-yangming"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 44, y: 11,
  },
  {
    id: "tp-yangming",
    name: "陽明山",
    county: "台北市",
    element: "fire",
    terrain: "火山地形",
    description: "古老火山地帶，地底熱能噴湧，火靈在硫磺煙霧中起舞，危險而神秘。",
    landmarks: ["陽明山國家公園", "竹子湖", "小油坑", "擎天崗"],
    dangerLevel: 3,
    connections: ["tp-beitou", "tp-shilin"],
    travelTime: 50,
    monsterLevel: [6, 14],
    x: 43, y: 9,
  },
  {
    id: "tp-wanhua",
    name: "萬華龍山",
    county: "台北市",
    element: "earth",
    terrain: "古城區",
    description: "台北最古老的街區，土靈能量深厚，龍山寺香火鼎盛，靈氣匯聚。",
    landmarks: ["龍山寺", "艋舺夜市", "剝皮寮歷史街區", "西門町"],
    dangerLevel: 1,
    connections: ["tp-zhongzheng", "tp-datong", "xindian-zhonghe"],
    travelTime: 30,
    monsterLevel: [1, 5],
    x: 45, y: 20,
  },
  {
    id: "tp-datong",
    name: "大同迪化",
    county: "台北市",
    element: "earth",
    terrain: "老街商圈",
    description: "百年老街，南北貨飄香，土靈精靈藏在古老倉庫的磚縫之間。",
    landmarks: ["迪化街", "大稻埕碼頭", "霞海城隍廟", "永樂市場"],
    dangerLevel: 1,
    connections: ["tp-wanhua", "tp-zhongshan", "tp-neihu"],
    travelTime: 30,
    monsterLevel: [1, 5],
    x: 46, y: 18,
  },
  {
    id: "tp-neihu",
    name: "內湖科技園",
    county: "台北市",
    element: "metal",
    terrain: "科技園區",
    description: "高科技園區，金屬靈能在電路板間流動，機械怪物偶爾從廢棄廠房竄出。",
    landmarks: ["內湖科技園區", "碧山巖", "大溝溪親水公園", "內湖夜市"],
    dangerLevel: 2,
    connections: ["tp-zhongshan", "tp-shilin", "tp-nangang", "xizhi-main"],
    travelTime: 35,
    monsterLevel: [3, 8],
    x: 51, y: 16,
  },
  {
    id: "tp-nangang",
    name: "南港展覽館",
    county: "台北市",
    element: "metal",
    terrain: "展覽商業區",
    description: "現代化展覽中心，金屬靈氣在巨型建築間迴盪，是商人與冒險者的交會點。",
    landmarks: ["南港展覽館", "中央研究院", "南港軟體園區", "南港車站"],
    dangerLevel: 2,
    connections: ["tp-xinyi", "tp-neihu", "xizhi-main"],
    travelTime: 35,
    monsterLevel: [3, 9],
    x: 53, y: 19,
  },
  {
    id: "tp-wenshan",
    name: "文山貓空",
    county: "台北市",
    element: "wood",
    terrain: "茶山丘陵",
    description: "茶香飄逸的山丘，木靈能量在茶園間流動，貓空纜車穿越雲霧。",
    landmarks: ["貓空纜車", "指南宮", "木柵動物園", "政治大學"],
    dangerLevel: 2,
    connections: ["tp-daan", "xindian-main"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 47, y: 24,
  },
  {
    id: "tp-songshan",
    name: "松山文創",
    county: "台北市",
    element: "fire",
    terrain: "文創園區",
    description: "舊菸廠改建的文創基地，創意火焰在磚牆間燃燒，藝術家與靈獸共存。",
    landmarks: ["松山文創園區", "饒河街夜市", "慈祐宮", "松山機場"],
    dangerLevel: 1,
    connections: ["tp-xinyi", "tp-zhongshan", "tp-neihu"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 50, y: 18,
  },
  {
    id: "tp-muzha",
    name: "木柵仙跡岩",
    county: "台北市",
    element: "wood",
    terrain: "郊山步道",
    description: "仙跡岩上古石刻字，木靈守護著這片山林，登頂可俯瞰台北盆地。",
    landmarks: ["仙跡岩步道", "景美夜市", "景美溪畔", "木柵公園"],
    dangerLevel: 2,
    connections: ["tp-wenshan", "tp-daan", "xindian-main"],
    travelTime: 35,
    monsterLevel: [3, 8],
    x: 47, y: 23,
  },
  {
    id: "tp-shezidao",
    name: "社子島濕地",
    county: "台北市",
    element: "water",
    terrain: "河岸濕地",
    description: "淡水河與基隆河交匯的孤島，水靈在蘆葦叢中低語，候鳥與水靈獸共棲。",
    landmarks: ["社子島", "基隆河", "淡水河岸", "葫蘆堵"],
    dangerLevel: 2,
    connections: ["tp-datong", "tp-shilin"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 44, y: 16,
  },
  {
    id: "tp-jingmei",
    name: "景美溪谷",
    county: "台北市",
    element: "water",
    terrain: "溪谷步道",
    description: "景美溪沿岸的翠綠步道，水靈能量清澈，是修煉水系技能的絕佳之地。",
    landmarks: ["景美溪自行車道", "景美人權文化園區", "景美老街", "羅斯福路商圈"],
    dangerLevel: 1,
    connections: ["tp-wenshan", "tp-muzha", "xindian-main"],
    travelTime: 30,
    monsterLevel: [1, 6],
    x: 47, y: 25,
  },

  // ════════════════════════════════════════
  // 新北市（16 節點）
  // ════════════════════════════════════════
  {
    id: "nb-banqiao",
    name: "板橋府中",
    county: "新北市",
    element: "earth",
    terrain: "都市中心",
    description: "新北市政中心，土靈能量穩固，是通往各地的交通樞紐。",
    landmarks: ["板橋車站", "新北市政府", "林家花園", "府中商圈"],
    dangerLevel: 1,
    connections: ["tp-wanhua", "nb-zhonghe", "nb-tucheng", "nb-xinzhuang"],
    travelTime: 30,
    monsterLevel: [1, 5],
    x: 44, y: 22,
  },
  {
    id: "nb-zhonghe",
    name: "中和南勢角",
    county: "新北市",
    element: "earth",
    terrain: "住宅商業區",
    description: "多元文化交融的城區，土靈能量在廟宇與市場間流動。",
    landmarks: ["南勢角商圈", "圓通寺", "中和烘爐地", "景安商圈"],
    dangerLevel: 1,
    connections: ["nb-banqiao", "tp-daan", "nb-yonghe", "xindian-main"],
    travelTime: 30,
    monsterLevel: [1, 5],
    x: 46, y: 23,
  },
  {
    id: "nb-yonghe",
    name: "永和豆漿",
    county: "新北市",
    element: "fire",
    terrain: "老城商圈",
    description: "以豆漿聞名的老城區，火靈能量在熱騰騰的早餐香氣中升騰。",
    landmarks: ["永和豆漿大王", "永和世界豆漿", "頂溪商圈", "永和公園"],
    dangerLevel: 1,
    connections: ["nb-zhonghe", "tp-daan", "nb-banqiao"],
    travelTime: 25,
    monsterLevel: [1, 5],
    x: 46, y: 22,
  },
  {
    id: "nb-xinzhuang",
    name: "新莊廟街",
    county: "新北市",
    element: "fire",
    terrain: "廟宇商圈",
    description: "古廟林立的老街，火靈香火鼎盛，武廟前的廣場常有靈獸出沒。",
    landmarks: ["新莊廟街", "武聖廟", "新莊棒球場", "頭前重劃區"],
    dangerLevel: 1,
    connections: ["nb-banqiao", "nb-sanchong", "taoyuan-guishan"],
    travelTime: 35,
    monsterLevel: [1, 6],
    x: 42, y: 20,
  },
  {
    id: "nb-sanchong",
    name: "三重重新橋",
    county: "新北市",
    element: "water",
    terrain: "河岸都市",
    description: "淡水河畔的工業城區，水靈在橋下河流中湧動，夜晚霓虹倒映水面。",
    landmarks: ["重新橋", "三重商圈", "三重棒球場", "淡水河自行車道"],
    dangerLevel: 1,
    connections: ["nb-xinzhuang", "nb-banqiao", "tp-datong"],
    travelTime: 30,
    monsterLevel: [1, 5],
    x: 44, y: 19,
  },
  {
    id: "nb-tucheng",
    name: "土城承天禪寺",
    county: "新北市",
    element: "wood",
    terrain: "山林寺廟",
    description: "山腰上的古老禪寺，木靈能量在松林間流動，登山步道上常有木靈獸出沒。",
    landmarks: ["承天禪寺", "土城桐花公園", "土城工業區", "清水祖師廟"],
    dangerLevel: 2,
    connections: ["nb-banqiao", "nb-sanxia"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 42, y: 24,
  },
  {
    id: "nb-sanxia",
    name: "三峽老街",
    county: "新北市",
    element: "wood",
    terrain: "古街山城",
    description: "保存完好的巴洛克式老街，木靈能量在古建築的紅磚間流動，染布坊香氣四溢。",
    landmarks: ["三峽老街", "三峽祖師廟", "鶯歌陶瓷博物館", "三峽河"],
    dangerLevel: 2,
    connections: ["nb-tucheng", "nb-yingge", "taoyuan-daxi"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 40, y: 25,
  },
  {
    id: "nb-yingge",
    name: "鶯歌陶瓷",
    county: "新北市",
    element: "earth",
    terrain: "陶瓷小鎮",
    description: "陶瓷之都，土靈能量在窯火中凝聚，陶器碎片間藏有土靈精靈。",
    landmarks: ["鶯歌陶瓷博物館", "鶯歌老街", "陶瓷觀光工廠", "三鶯大橋"],
    dangerLevel: 2,
    connections: ["nb-sanxia", "nb-zhonghe", "taoyuan-daxi"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 40, y: 26,
  },
  {
    id: "nb-xindian",
    name: "新店碧潭",
    county: "新北市",
    element: "water",
    terrain: "潭邊山城",
    description: "碧潭清澈如翡翠，水靈在潭底深處沉睡，吊橋上常有靈氣湧現。",
    landmarks: ["碧潭風景區", "新店吊橋", "小粗坑古道", "直潭水庫"],
    dangerLevel: 2,
    connections: ["nb-zhonghe", "tp-wenshan", "nb-wulai"],
    travelTime: 35,
    monsterLevel: [3, 9],
    x: 47, y: 27,
  },
  {
    id: "nb-wulai",
    name: "烏來溫泉",
    county: "新北市",
    element: "water",
    terrain: "山地溫泉",
    description: "泰雅族聖地，溫泉蒸氣中藏有古老的水靈，瀑布旁是強大怪物的巢穴。",
    landmarks: ["烏來瀑布", "烏來溫泉", "泰雅民族博物館", "烏來老街"],
    dangerLevel: 3,
    connections: ["nb-xindian", "nb-pinglin"],
    travelTime: 55,
    monsterLevel: [7, 15],
    x: 46, y: 30,
  },
  {
    id: "nb-pinglin",
    name: "坪林茶鄉",
    county: "新北市",
    element: "wood",
    terrain: "茶山溪谷",
    description: "包種茶的故鄉，木靈能量在茶葉間凝聚，北勢溪畔的石頭縫中藏有木靈獸。",
    landmarks: ["坪林茶業博物館", "北勢溪", "坪林老街", "翡翠水庫"],
    dangerLevel: 3,
    connections: ["nb-wulai", "yilan-toucheng"],
    travelTime: 60,
    monsterLevel: [7, 15],
    x: 50, y: 28,
  },
  {
    id: "nb-danshui",
    name: "淡水老街",
    county: "新北市",
    element: "water",
    terrain: "河口古城",
    description: "淡水河出海口的古老港城，水靈在夕陽映照的河面上起舞，紅毛城見證百年歷史。",
    landmarks: ["淡水老街", "紅毛城", "淡水漁人碼頭", "滬尾砲台"],
    dangerLevel: 2,
    connections: ["nb-bali", "nb-sanchong", "tp-shilin"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 40, y: 14,
  },
  {
    id: "nb-bali",
    name: "八里左岸",
    county: "新北市",
    element: "water",
    terrain: "河口海岸",
    description: "淡水河左岸的寧靜海岸，水靈在海風中飛翔，十三行博物館訴說史前文明。",
    landmarks: ["十三行博物館", "八里左岸公園", "觀音山", "八里渡船頭"],
    dangerLevel: 2,
    connections: ["nb-danshui", "nb-linkou"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 38, y: 16,
  },
  {
    id: "nb-linkou",
    name: "林口台地",
    county: "新北市",
    element: "metal",
    terrain: "高原台地",
    description: "海拔較高的台地，金靈能量在強勁海風中流動，林口長庚醫院如城堡般矗立。",
    landmarks: ["林口長庚醫院", "林口奧特萊斯", "林口台地", "南勢角山"],
    dangerLevel: 2,
    connections: ["nb-bali", "nb-sanchong", "taoyuan-guishan"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 38, y: 19,
  },
  {
    id: "nb-ruifang",
    name: "瑞芳九份",
    county: "新北市",
    element: "metal",
    terrain: "礦山聚落",
    description: "昔日黃金礦山，金靈能量在廢棄礦坑中積聚，九份老街的紅燈籠在雨霧中搖曳。",
    landmarks: ["九份老街", "金瓜石黃金博物館", "基隆山", "陰陽海"],
    dangerLevel: 3,
    connections: ["nb-jiufen-shenao", "keelung-main"],
    travelTime: 50,
    monsterLevel: [6, 14],
    x: 57, y: 17,
  },
  {
    id: "nb-jiufen-shenao",
    name: "深澳漁港",
    county: "新北市",
    element: "water",
    terrain: "漁港海岸",
    description: "隱藏在山崖間的漁港，水靈在岩礁間嬉戲，象鼻岩是水靈獸的棲息地。",
    landmarks: ["深澳漁港", "象鼻岩", "深澳岬角", "番仔澳"],
    dangerLevel: 3,
    connections: ["nb-ruifang", "keelung-main"],
    travelTime: 50,
    monsterLevel: [6, 14],
    x: 58, y: 16,
  },

  // ════════════════════════════════════════
  // 基隆市（6 節點）
  // ════════════════════════════════════════
  {
    id: "keelung-main",
    name: "基隆廟口",
    county: "基隆市",
    element: "water",
    terrain: "港口夜市",
    description: "雨都的著名廟口夜市，水靈在常年細雨中遊蕩，海港的鹹味混合著小吃香氣。",
    landmarks: ["基隆廟口夜市", "奠濟宮", "基隆港", "基隆火車站"],
    dangerLevel: 1,
    connections: ["nb-ruifang", "nb-jiufen-shenao", "keelung-zhongzheng", "keelung-badouzi"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 55, y: 14,
  },
  {
    id: "keelung-zhongzheng",
    name: "中正公園",
    county: "基隆市",
    element: "earth",
    terrain: "山頂公園",
    description: "俯瞰基隆港的山頂公園，土靈在巨型觀音像腳下守護，海風帶來遠方的靈氣。",
    landmarks: ["中正公園", "基隆觀音像", "大佛禪院", "基隆要塞司令部"],
    dangerLevel: 2,
    connections: ["keelung-main", "keelung-nuannuan"],
    travelTime: 30,
    monsterLevel: [3, 8],
    x: 55, y: 13,
  },
  {
    id: "keelung-badouzi",
    name: "八斗子漁港",
    county: "基隆市",
    element: "water",
    terrain: "漁港海岸",
    description: "北台灣最大的漁港，水靈在漁船間穿梭，潮境公園是觀察海洋靈獸的好地方。",
    landmarks: ["八斗子漁港", "潮境公園", "望幽谷", "碧砂漁港"],
    dangerLevel: 2,
    connections: ["keelung-main", "keelung-heping"],
    travelTime: 35,
    monsterLevel: [3, 9],
    x: 57, y: 13,
  },
  {
    id: "keelung-heping",
    name: "和平島",
    county: "基隆市",
    element: "water",
    terrain: "海島地質",
    description: "奇特地質景觀的小島，水靈在海蝕洞中棲息，豆腐岩是古老水靈的傑作。",
    landmarks: ["和平島地質公園", "豆腐岩", "番仔澳", "社寮島"],
    dangerLevel: 3,
    connections: ["keelung-badouzi", "keelung-main"],
    travelTime: 40,
    monsterLevel: [5, 12],
    x: 56, y: 12,
  },
  {
    id: "keelung-nuannuan",
    name: "暖暖溪谷",
    county: "基隆市",
    element: "wood",
    terrain: "溪谷步道",
    description: "暖暖溪沿岸的翠綠步道，木靈能量清新，是城市中難得的自然秘境。",
    landmarks: ["暖暖親水公園", "暖暖老街", "暖暖車站", "東勢坑溪"],
    dangerLevel: 2,
    connections: ["keelung-zhongzheng", "keelung-main"],
    travelTime: 35,
    monsterLevel: [3, 8],
    x: 54, y: 15,
  },
  {
    id: "keelung-dawulun",
    name: "大武崙砲台",
    county: "基隆市",
    element: "metal",
    terrain: "古砲台遺址",
    description: "清朝古砲台遺址，金靈能量在鐵鏽砲管間凝聚，海岸線一覽無遺。",
    landmarks: ["大武崙砲台", "大武崙海水浴場", "協和電廠", "外木山海岸"],
    dangerLevel: 2,
    connections: ["keelung-main", "nb-danshui"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 53, y: 12,
  },

  // ════════════════════════════════════════
  // 桃園市（12 節點）
  // ════════════════════════════════════════
  {
    id: "taoyuan-zhongli",
    name: "中壢夜市",
    county: "桃園市",
    element: "fire",
    terrain: "都市商圈",
    description: "桃園最熱鬧的商圈，火靈能量在夜市攤販的爐火間跳動，多元族群匯聚。",
    landmarks: ["中壢夜市", "SOGO百貨", "中壢車站", "老街溪"],
    dangerLevel: 1,
    connections: ["taoyuan-main", "taoyuan-pingzhen", "hsinchu-zhudong"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 37, y: 24,
  },
  {
    id: "taoyuan-main",
    name: "桃園市區",
    county: "桃園市",
    element: "earth",
    terrain: "都市中心",
    description: "桃園市政中心，土靈能量穩固，是北台灣重要的交通樞紐。",
    landmarks: ["桃園火車站", "桃園神社", "桃園市政府", "南崁溪"],
    dangerLevel: 1,
    connections: ["taoyuan-zhongli", "taoyuan-guishan", "nb-linkou"],
    travelTime: 30,
    monsterLevel: [1, 6],
    x: 36, y: 22,
  },
  {
    id: "taoyuan-guishan",
    name: "龜山工業區",
    county: "桃園市",
    element: "metal",
    terrain: "工業科技區",
    description: "工業與科技並存的城區，金靈能量在廠房間流動，林口台地邊緣藏有金屬怪物。",
    landmarks: ["龜山工業區", "長庚大學", "龜山鄉公所", "壽山巖"],
    dangerLevel: 2,
    connections: ["taoyuan-main", "nb-linkou", "nb-sanchong"],
    travelTime: 35,
    monsterLevel: [3, 8],
    x: 38, y: 21,
  },
  {
    id: "taoyuan-daxi",
    name: "大溪老街",
    county: "桃園市",
    element: "wood",
    terrain: "古街河岸",
    description: "大漢溪畔的百年老街，木靈能量在古建築的木雕間流動，豆干香氣飄散四方。",
    landmarks: ["大溪老街", "大溪木藝生態博物館", "中正公園", "大漢溪"],
    dangerLevel: 2,
    connections: ["nb-sanxia", "nb-yingge", "taoyuan-fuxing"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 39, y: 27,
  },
  {
    id: "taoyuan-fuxing",
    name: "復興角板山",
    county: "桃園市",
    element: "wood",
    terrain: "山地部落",
    description: "泰雅族傳統領域，木靈能量在原始森林中澎湃，拉拉山神木群是古老木靈的聖地。",
    landmarks: ["角板山公園", "拉拉山神木群", "巴陵古道", "石門水庫"],
    dangerLevel: 4,
    connections: ["taoyuan-daxi", "taoyuan-shimen"],
    travelTime: 70,
    monsterLevel: [10, 20],
    x: 38, y: 31,
  },
  {
    id: "taoyuan-shimen",
    name: "石門水庫",
    county: "桃園市",
    element: "water",
    terrain: "水庫湖泊",
    description: "北台灣最大水庫，水靈能量深厚，湖面倒映山影，水底藏有古老的水靈王。",
    landmarks: ["石門水庫", "阿姆坪", "石門活魚餐廳", "大壩"],
    dangerLevel: 3,
    connections: ["taoyuan-daxi", "taoyuan-fuxing", "taoyuan-zhongli"],
    travelTime: 55,
    monsterLevel: [7, 16],
    x: 37, y: 28,
  },
  {
    id: "taoyuan-pingzhen",
    name: "平鎮客家",
    county: "桃園市",
    element: "earth",
    terrain: "客家聚落",
    description: "客家文化濃厚的城區，土靈能量在客家伙房的磚牆間流動，義民廟香火鼎盛。",
    landmarks: ["平鎮義民廟", "平鎮工業區", "龍潭大池", "客家文化館"],
    dangerLevel: 1,
    connections: ["taoyuan-zhongli", "taoyuan-longtan"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 37, y: 26,
  },
  {
    id: "taoyuan-longtan",
    name: "龍潭大池",
    county: "桃園市",
    element: "water",
    terrain: "湖泊公園",
    description: "龍潭大池波光粼粼，水靈在荷花叢中嬉戲，湖心亭是旅人休憩的好地方。",
    landmarks: ["龍潭大池", "龍潭觀光茶園", "龍潭石門活魚", "中央大學"],
    dangerLevel: 2,
    connections: ["taoyuan-pingzhen", "taoyuan-shimen", "hsinchu-zhudong"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 37, y: 27,
  },
  {
    id: "taoyuan-airport",
    name: "桃園國際機場",
    county: "桃園市",
    element: "metal",
    terrain: "機場航運",
    description: "台灣最大的國際機場，金靈能量在航廈的鋼鐵結構間流動，是通往世界的門戶。",
    landmarks: ["桃園國際機場", "機場捷運", "航空城", "大園海岸"],
    dangerLevel: 2,
    connections: ["taoyuan-main", "nb-bali", "taoyuan-guanyin"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 34, y: 20,
  },
  {
    id: "taoyuan-guanyin",
    name: "觀音海岸",
    county: "桃園市",
    element: "water",
    terrain: "海岸濕地",
    description: "桃園海岸線的濕地公園，水靈在潮間帶的泥灘上嬉戲，風力發電機在海風中旋轉。",
    landmarks: ["觀音工業區", "草漯沙丘", "許厝港濕地", "白玉海灘"],
    dangerLevel: 2,
    connections: ["taoyuan-airport", "taoyuan-zhongli"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 33, y: 22,
  },
  {
    id: "taoyuan-yangmei",
    name: "楊梅茶園",
    county: "桃園市",
    element: "wood",
    terrain: "茶園丘陵",
    description: "桃園茶鄉，木靈能量在茶園的綠意中流動，紅茶香氣是木靈獸最愛的氣息。",
    landmarks: ["楊梅茶園", "楊梅老街", "秀才窩", "楊梅車站"],
    dangerLevel: 2,
    connections: ["taoyuan-zhongli", "taoyuan-pingzhen", "hsinchu-zhudong"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 36, y: 27,
  },
  {
    id: "taoyuan-luzhu",
    name: "蘆竹南崁",
    county: "桃園市",
    element: "fire",
    terrain: "商業住宅區",
    description: "緊鄰機場的新興商業區，火靈能量在石化工業的煙囪間燃燒，南崁溪畔有靈獸出沒。",
    landmarks: ["南崁溪", "蘆竹工業區", "南崁廟", "蘆竹五福宮"],
    dangerLevel: 1,
    connections: ["taoyuan-airport", "taoyuan-main"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 35, y: 21,
  },

  // ════════════════════════════════════════
  // 新竹市（6 節點）
  // ════════════════════════════════════════
  {
    id: "hsinchu-city",
    name: "新竹城隍廟",
    county: "新竹市",
    element: "fire",
    terrain: "古城商圈",
    description: "台灣最著名的城隍廟之一，火靈香火旺盛，廟口小吃是旅人補充體力的好去處。",
    landmarks: ["新竹城隍廟", "新竹火車站", "東門城", "新竹公園"],
    dangerLevel: 1,
    connections: ["hsinchu-zhudong", "hsinchu-xiangshan", "hsinchu-science"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 33, y: 30,
  },
  {
    id: "hsinchu-science",
    name: "新竹科學園區",
    county: "新竹市",
    element: "metal",
    terrain: "科技園區",
    description: "台灣矽谷，金靈能量在晶圓廠的精密設備間流動，是現代金靈獸的棲息地。",
    landmarks: ["新竹科學工業園區", "清華大學", "交通大學", "工研院"],
    dangerLevel: 2,
    connections: ["hsinchu-city", "hsinchu-zhudong"],
    travelTime: 35,
    monsterLevel: [3, 9],
    x: 33, y: 29,
  },
  {
    id: "hsinchu-xiangshan",
    name: "香山海岸",
    county: "新竹市",
    element: "water",
    terrain: "海岸濕地",
    description: "新竹海岸的泥灘濕地，水靈在潮汐間起伏，招潮蟹與水靈獸共享這片領域。",
    landmarks: ["香山濕地", "南寮漁港", "十七公里海岸線", "新竹漁港"],
    dangerLevel: 2,
    connections: ["hsinchu-city", "miaoli-zhunan"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 31, y: 31,
  },
  {
    id: "hsinchu-zhudong",
    name: "竹東客家",
    county: "新竹縣",
    element: "earth",
    terrain: "客家山城",
    description: "客家文化的重鎮，土靈能量在傳統夥房的紅磚間流動，竹東市場飄散著客家美食香氣。",
    landmarks: ["竹東市場", "竹東林業展示館", "竹東圳", "二重埔文化景觀"],
    dangerLevel: 2,
    connections: ["hsinchu-city", "taoyuan-zhongli", "hsinchu-jianshi"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 34, y: 31,
  },
  {
    id: "hsinchu-jianshi",
    name: "尖石泰雅",
    county: "新竹縣",
    element: "wood",
    terrain: "山地部落",
    description: "泰雅族的神聖山地，木靈能量在原始森林中澎湃，司馬庫斯巨木群是木靈王的領地。",
    landmarks: ["司馬庫斯", "鎮西堡神木群", "秀巒溫泉", "李棟山古堡"],
    dangerLevel: 4,
    connections: ["hsinchu-zhudong", "taoyuan-fuxing"],
    travelTime: 80,
    monsterLevel: [12, 22],
    x: 36, y: 33,
  },
  {
    id: "hsinchu-beipu",
    name: "北埔老街",
    county: "新竹縣",
    element: "earth",
    terrain: "客家老街",
    description: "保存完好的客家古聚落，土靈能量在百年伙房的石板間流動，擂茶香氣吸引靈獸。",
    landmarks: ["北埔老街", "天水堂", "慈天宮", "金廣福公館"],
    dangerLevel: 2,
    connections: ["hsinchu-zhudong", "miaoli-zhunan"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 34, y: 33,
  },
  {
    id: "hsinchu-city-glass",
    name: "新竹玻璃工藝博物館",
    county: "新竹市",
    element: "metal",
    terrain: "文化園區",
    description: "新竹以玻璃工藝聞名全台，金靈能量在精緻玻璃器皿中折射出七彩光芒，是金靈獸最愛的棲息地。",
    landmarks: ["新竹玻璃工藝博物館", "新竹市立動物園", "麗池公園", "新竹公園"],
    dangerLevel: 1,
    connections: ["hsinchu-city", "hsinchu-science"],
    travelTime: 25,
    monsterLevel: [2, 6],
    x: 32, y: 30,
  },
  {
    id: "hsinchu-city-nanliao",
    name: "南寮漁港",
    county: "新竹市",
    element: "water",
    terrain: "漁港海岸",
    description: "新竹最大的漁港，水靈在台灣海峽的漁船間穿梭，每年風箏節吸引各地旅人聚集。",
    landmarks: ["南寮漁港", "新竹漁港", "南寮舊漁港", "17公里海岸線"],
    dangerLevel: 2,
    connections: ["hsinchu-xiangshan", "hsinchu-city"],
    travelTime: 30,
    monsterLevel: [3, 8],
    x: 30, y: 30,
  },
  {
    id: "hsinchu-city-beimen",
    name: "北門街歷史區",
    county: "新竹市",
    element: "wood",
    terrain: "歷史街區",
    description: "新竹舊城區的心臟地帶，木靈能量在百年老樹的枝椏間流動，鄭氏家廟是旅人尋根的聖地。",
    landmarks: ["北門街", "長和宮", "鄭氏家廟", "新竹都城隍廟"],
    dangerLevel: 1,
    connections: ["hsinchu-city", "hsinchu-city-glass"],
    travelTime: 20,
    monsterLevel: [1, 5],
    x: 33, y: 30,
  },
  {
    id: "hsinchu-county-guanxi",
    name: "關西老街",
    county: "新竹縣",
    element: "wood",
    terrain: "客家老街",
    description: "關西是客家文化重鎮，木靈能量在老街的榕樹下流動，仙草是旅人補充靈力的聖品。",
    landmarks: ["關西老街", "關西仙草節", "牛欄河親水公園", "關西分駐所"],
    dangerLevel: 2,
    connections: ["hsinchu-zhudong", "taoyuan-daxi"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 35, y: 29,
  },
  {
    id: "hsinchu-county-wufeng",
    name: "五峰清泉部落",
    county: "新竹縣",
    element: "water",
    terrain: "原住民部落",
    description: "泰雅族清泉部落，水靈在上坪溪的清澈溪流中奔騰，張學良故居是旅人探索歷史的聖地。",
    landmarks: ["清泉溫泉", "張學良故居", "上坪溪", "清泉部落"],
    dangerLevel: 3,
    connections: ["hsinchu-jianshi", "hsinchu-zhudong"],
    travelTime: 60,
    monsterLevel: [8, 16],
    x: 36, y: 32,
  },
  {
    id: "hsinchu-county-emei",
    name: "峨眉湖茶鄉",
    county: "新竹縣",
    element: "earth",
    terrain: "湖泊茶園",
    description: "峨眉湖畔的茶鄉，土靈能量在肥沃茶園的土壤中蘊藏，東方美人茶是旅人必嚐的靈茶。",
    landmarks: ["峨眉湖", "東方美人茶產區", "峨眉慈天宮", "十二寮休閒農業區"],
    dangerLevel: 2,
    connections: ["hsinchu-beipu", "miaoli-zhunan"],
    travelTime: 35,
    monsterLevel: [3, 8],
    x: 33, y: 34,
  },

  // ════════════════════════════════════════
  // 苗栗縣（9 節點）
  // ════════════════════════════════════════
  {
    id: "miaoli-zhunan",
    name: "竹南海線",
    county: "苗栗縣",
    element: "water",
    terrain: "海岸平原",
    description: "苗栗海線的起點，水靈在台灣海峽的浪濤中翻滾，中港溪出海口是水靈聚集之地。",
    landmarks: ["竹南火車站", "中港溪", "竹南科學園區", "竹南老街"],
    dangerLevel: 2,
    connections: ["hsinchu-xiangshan", "miaoli-main", "hsinchu-beipu"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 32, y: 33,
  },
  {
    id: "miaoli-main",
    name: "苗栗市區",
    county: "苗栗縣",
    element: "earth",
    terrain: "山城市區",
    description: "客家文化首都，土靈能量在丘陵間流動，苗栗縣政府周邊是旅人的補給站。",
    landmarks: ["苗栗火車站", "苗栗縣政府", "苗栗客家文化園區", "苗栗老街"],
    dangerLevel: 2,
    connections: ["miaoli-zhunan", "miaoli-tongxiao", "miaoli-sanyi"],
    travelTime: 35,
    monsterLevel: [3, 8],
    x: 33, y: 35,
  },
  {
    id: "miaoli-tongxiao",
    name: "通霄海岸",
    county: "苗栗縣",
    element: "water",
    terrain: "海岸漁港",
    description: "苗栗最美的海岸線，水靈在白色沙灘上留下足跡，通霄神社俯瞰大海。",
    landmarks: ["通霄神社", "通霄海水浴場", "通霄漁港", "飛牛牧場"],
    dangerLevel: 2,
    connections: ["miaoli-main", "miaoli-yuanli"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 30, y: 35,
  },
  {
    id: "miaoli-yuanli",
    name: "苑裡藺草",
    county: "苗栗縣",
    element: "wood",
    terrain: "平原農村",
    description: "藺草編織的故鄉，木靈能量在草田間流動，傳統藺草帽是旅人的護身符。",
    landmarks: ["苑裡藺草文化館", "山腳國小百年校舍", "苑裡老街", "慈和宮"],
    dangerLevel: 1,
    connections: ["miaoli-tongxiao", "taichung-dajia"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 30, y: 37,
  },
  {
    id: "miaoli-sanyi",
    name: "三義木雕",
    county: "苗栗縣",
    element: "wood",
    terrain: "木雕山城",
    description: "台灣木雕之都，木靈能量在雕刻師的刀工間凝聚，每件木雕都藏有木靈的靈魂。",
    landmarks: ["三義木雕博物館", "木雕街", "龍騰斷橋", "勝興車站"],
    dangerLevel: 2,
    connections: ["miaoli-main", "miaoli-dahu"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 33, y: 37,
  },
  {
    id: "miaoli-dahu",
    name: "大湖草莓",
    county: "苗栗縣",
    element: "fire",
    terrain: "山谷農村",
    description: "台灣草莓的故鄉，火靈能量在紅色果實間燃燒，大湖酒莊的果酒香氣吸引靈獸。",
    landmarks: ["大湖草莓園", "大湖酒莊", "大湖公園", "薑麻園"],
    dangerLevel: 2,
    connections: ["miaoli-sanyi", "miaoli-shitan"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 34, y: 38,
  },
  {
    id: "miaoli-shitan",
    name: "獅潭仙山",
    county: "苗栗縣",
    element: "wood",
    terrain: "山林廟宇",
    description: "仙山靈洞宮香火鼎盛，木靈能量在原始山林中澎湃，是修煉的絕佳聖地。",
    landmarks: ["仙山靈洞宮", "獅潭老街", "百壽步道", "汶水老街"],
    dangerLevel: 3,
    connections: ["miaoli-dahu", "miaoli-nanzhuang"],
    travelTime: 55,
    monsterLevel: [6, 14],
    x: 35, y: 39,
  },
  {
    id: "miaoli-nanzhuang",
    name: "南庄老街",
    county: "苗栗縣",
    element: "earth",
    terrain: "山城老街",
    description: "賽夏族與客家文化交融的山城，土靈能量在古老的郵局建築間流動，桂花香氣瀰漫。",
    landmarks: ["南庄老街", "南庄郵局", "向天湖", "賽夏族文化"],
    dangerLevel: 3,
    connections: ["miaoli-shitan", "miaoli-zhunan"],
    travelTime: 55,
    monsterLevel: [6, 14],
    x: 34, y: 36,
  },
  {
    id: "miaoli-houlong",
    name: "後龍好望角",
    county: "苗栗縣",
    element: "water",
    terrain: "海岸丘陵",
    description: "俯瞰台灣海峽的絕美海岸，水靈在強勁的海風中飛翔，風力發電機如巨人般矗立。",
    landmarks: ["好望角", "後龍海水浴場", "後龍溪", "客家圓樓"],
    dangerLevel: 2,
    connections: ["miaoli-zhunan", "miaoli-tongxiao"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 30, y: 34,
  },

  // ════════════════════════════════════════
  // 台中市（14 節點）
  // ════════════════════════════════════════
  {
    id: "taichung-main",
    name: "台中市區",
    county: "台中市",
    element: "fire",
    terrain: "都市中心",
    description: "台灣第二大都市，火靈能量在繁華街道間燃燒，宮原眼科的美食香氣吸引四方旅人。",
    landmarks: ["台中火車站", "宮原眼科", "第二市場", "台中公園"],
    dangerLevel: 1,
    connections: ["taichung-xitun", "taichung-nantun", "taichung-beitun", "taichung-fengyuan"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 36, y: 43,
  },
  {
    id: "taichung-xitun",
    name: "西屯逢甲",
    county: "台中市",
    element: "fire",
    terrain: "大學商圈",
    description: "逢甲夜市是全台最大夜市之一，火靈能量在攤販的爐火間跳動，美食靈獸在此聚集。",
    landmarks: ["逢甲夜市", "逢甲大學", "台中港路商圈", "秋紅谷"],
    dangerLevel: 1,
    connections: ["taichung-main", "taichung-dali", "taichung-qingshui"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 35, y: 43,
  },
  {
    id: "taichung-nantun",
    name: "南屯老街",
    county: "台中市",
    element: "earth",
    terrain: "老街聚落",
    description: "台中最古老的聚落之一，土靈能量在萬和宮的香火中凝聚，犁頭店老街訴說百年歷史。",
    landmarks: ["萬和宮", "犁頭店老街", "南屯老街", "文心森林公園"],
    dangerLevel: 1,
    connections: ["taichung-main", "taichung-wufeng", "taichung-dali"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 36, y: 44,
  },
  {
    id: "taichung-beitun",
    name: "北屯大坑",
    county: "台中市",
    element: "wood",
    terrain: "郊山步道",
    description: "台中最受歡迎的郊山步道，木靈能量在大坑山林間流動，登頂可俯瞰台中盆地。",
    landmarks: ["大坑步道", "大坑風景區", "新社花海", "北屯老街"],
    dangerLevel: 2,
    connections: ["taichung-main", "taichung-fengyuan", "taichung-xinshe"],
    travelTime: 35,
    monsterLevel: [3, 9],
    x: 37, y: 42,
  },
  {
    id: "taichung-fengyuan",
    name: "豐原廟東",
    county: "台中市",
    element: "fire",
    terrain: "廟宇商圈",
    description: "豐原廟東夜市香氣四溢，火靈能量在廟宇香火中升騰，慈濟宮是旅人祈福的聖地。",
    landmarks: ["豐原廟東夜市", "慈濟宮", "豐原火車站", "葫蘆墩公園"],
    dangerLevel: 1,
    connections: ["taichung-main", "taichung-beitun", "taichung-dongshi"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 37, y: 41,
  },
  {
    id: "taichung-dongshi",
    name: "東勢大雪山",
    county: "台中市",
    element: "wood",
    terrain: "山林農村",
    description: "大雪山林道是賞鳥聖地，木靈能量在原始森林中澎湃，高山蘋果是旅人的珍貴補給。",
    landmarks: ["大雪山國家森林遊樂區", "東勢林場", "東勢老街", "客家文化園區"],
    dangerLevel: 3,
    connections: ["taichung-fengyuan", "taichung-heping"],
    travelTime: 60,
    monsterLevel: [7, 16],
    x: 39, y: 40,
  },
  {
    id: "taichung-heping",
    name: "和平梨山",
    county: "台中市",
    element: "metal",
    terrain: "高山農業",
    description: "台灣最高的農業聚落，金靈能量在高山冷冽空氣中凝聚，梨山的水蜜桃是金靈獸的最愛。",
    landmarks: ["梨山賓館", "福壽山農場", "武陵農場", "合歡山"],
    dangerLevel: 5,
    connections: ["taichung-dongshi", "nantou-renai"],
    travelTime: 90,
    monsterLevel: [15, 25],
    x: 40, y: 38,
  },
  {
    id: "taichung-xinshe",
    name: "新社花海",
    county: "台中市",
    element: "wood",
    terrain: "高原花田",
    description: "每年秋冬的花海盛典，木靈能量在繁花間流動，薰衣草森林是木靈精靈的樂園。",
    landmarks: ["新社花海", "薰衣草森林", "中社觀光花市", "新社古堡"],
    dangerLevel: 2,
    connections: ["taichung-beitun", "taichung-dongshi"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 38, y: 42,
  },
  {
    id: "taichung-wufeng",
    name: "霧峰林家",
    county: "台中市",
    element: "earth",
    terrain: "古宅園林",
    description: "台灣最大的傳統民居建築群，土靈能量在百年古宅的磚瓦間凝聚，921地震博物館記錄大地的力量。",
    landmarks: ["霧峰林家花園", "921地震教育園區", "亞洲現代美術館", "霧峰農會酒莊"],
    dangerLevel: 2,
    connections: ["taichung-nantun", "taichung-dali", "nantou-caotun"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 37, y: 45,
  },
  {
    id: "taichung-dali",
    name: "大里溪畔",
    county: "台中市",
    element: "water",
    terrain: "溪畔城區",
    description: "大里溪沿岸的城區，水靈在溪流中嬉戲，大里杙老街訴說著清代移民的故事。",
    landmarks: ["大里溪", "大里杙老街", "大里藝術館", "草湖溪"],
    dangerLevel: 1,
    connections: ["taichung-xitun", "taichung-nantun", "taichung-wufeng"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 36, y: 45,
  },
  {
    id: "taichung-qingshui",
    name: "清水高美",
    county: "台中市",
    element: "water",
    terrain: "海岸濕地",
    description: "高美濕地是台灣最美的夕陽觀賞地，水靈在夕陽映照的泥灘上起舞，風力發電機如守護神。",
    landmarks: ["高美濕地", "清水老街", "清水眷村文化園區", "大甲溪出海口"],
    dangerLevel: 2,
    connections: ["taichung-xitun", "taichung-dajia"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 33, y: 41,
  },
  {
    id: "taichung-dajia",
    name: "大甲媽祖",
    county: "台中市",
    element: "fire",
    terrain: "廟宇聖地",
    description: "媽祖信仰的聖地，火靈香火最旺盛之處，每年媽祖遶境是全台最大的宗教盛典。",
    landmarks: ["大甲鎮瀾宮", "大甲帽蓆文化館", "鐵砧山", "大甲溪"],
    dangerLevel: 2,
    connections: ["taichung-qingshui", "miaoli-yuanli", "taichung-fengyuan"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 33, y: 39,
  },
  {
    id: "taichung-wuqi",
    name: "梧棲漁港",
    county: "台中市",
    element: "water",
    terrain: "漁港碼頭",
    description: "台中港旁的漁港，水靈在漁船間穿梭，新鮮海產是旅人補充體力的最佳選擇。",
    landmarks: ["梧棲漁港", "台中港", "梧棲老街", "高美大橋"],
    dangerLevel: 2,
    connections: ["taichung-qingshui", "taichung-xitun"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 32, y: 42,
  },
  {
    id: "taichung-taiping",
    name: "太平頭汴坑",
    county: "台中市",
    element: "wood",
    terrain: "山林溪谷",
    description: "頭汴坑溪沿岸的山林步道，木靈能量清新，是台中市民週末踏青的秘境。",
    landmarks: ["頭汴坑溪", "太平老街", "坪林步道", "蝙蝠洞"],
    dangerLevel: 2,
    connections: ["taichung-beitun", "taichung-wufeng"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 38, y: 43,
  },

  // ════════════════════════════════════════
  // 彰化縣（9 節點）
  // ════════════════════════════════════════
  {
    id: "changhua-main",
    name: "彰化大佛",
    county: "彰化縣",
    element: "earth",
    terrain: "山丘廟宇",
    description: "彰化大佛俯瞰整個彰化平原，土靈能量在八卦山上凝聚，是旅人祈求平安的聖地。",
    landmarks: ["彰化大佛", "八卦山", "彰化火車站", "彰化孔廟"],
    dangerLevel: 1,
    connections: ["changhua-lukang", "changhua-yuanlin", "changhua-tianzhong", "nantou-caotun"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 34, y: 47,
  },
  {
    id: "changhua-lukang",
    name: "鹿港老街",
    county: "彰化縣",
    element: "earth",
    terrain: "古港老街",
    description: "台灣保存最完好的清代古街，土靈能量在百年建築間流動，鹿港天后宮香火千年不斷。",
    landmarks: ["鹿港天后宮", "鹿港老街", "鹿港龍山寺", "九曲巷"],
    dangerLevel: 2,
    connections: ["changhua-main", "changhua-xianxi"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 32, y: 46,
  },
  {
    id: "changhua-xianxi",
    name: "線西海岸",
    county: "彰化縣",
    element: "water",
    terrain: "海岸濕地",
    description: "彰化海岸的濕地公園，水靈在潮間帶的泥灘上嬉戲，是候鳥遷徙的重要棲地。",
    landmarks: ["彰化海岸保護區", "線西鄉海岸", "彰濱工業區", "王功漁港"],
    dangerLevel: 2,
    connections: ["changhua-lukang", "changhua-fuxing"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 30, y: 46,
  },
  {
    id: "changhua-fuxing",
    name: "福興穀倉",
    county: "彰化縣",
    element: "earth",
    terrain: "農村平原",
    description: "台灣米倉的核心地帶，土靈能量在稻田間流動，日式穀倉是土靈精靈的棲息地。",
    landmarks: ["福興穀倉", "福興鄉農村", "福興海岸", "彰化平原"],
    dangerLevel: 1,
    connections: ["changhua-xianxi", "changhua-lukang"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 31, y: 47,
  },
  {
    id: "changhua-yuanlin",
    name: "員林果鄉",
    county: "彰化縣",
    element: "wood",
    terrain: "果園丘陵",
    description: "台灣水果的重要產地，木靈能量在果園間流動，員林百果山的荔枝香氣吸引靈獸。",
    landmarks: ["員林百果山", "員林老街", "員林車站", "員林公園"],
    dangerLevel: 1,
    connections: ["changhua-main", "changhua-tianzhong", "yunlin-xiluo"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 34, y: 48,
  },
  {
    id: "changhua-tianzhong",
    name: "田中鐵道",
    county: "彰化縣",
    element: "metal",
    terrain: "鐵道小鎮",
    description: "縱貫鐵路的重要車站，金靈能量在鐵軌間流動，田中老街保存著鐵道文化的記憶。",
    landmarks: ["田中車站", "田中老街", "田中公園", "田中溪"],
    dangerLevel: 1,
    connections: ["changhua-main", "changhua-yuanlin", "nantou-caotun"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 35, y: 49,
  },
  {
    id: "changhua-ershui",
    name: "二水集集線",
    county: "彰化縣",
    element: "water",
    terrain: "溪畔鐵道",
    description: "集集支線的起點，水靈在濁水溪畔流動，二水鄉是台灣最重要的水資源補給站。",
    landmarks: ["二水車站", "集集支線", "濁水溪", "二水鄉公所"],
    dangerLevel: 2,
    connections: ["changhua-tianzhong", "nantou-jiji"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 35, y: 50,
  },
  {
    id: "changhua-baguashan",
    name: "八卦山脈",
    county: "彰化縣",
    element: "earth",
    terrain: "山脈稜線",
    description: "縱貫彰化的山脈稜線，土靈能量在山頂強風中凝聚，是觀賞彰化平原的最佳視角。",
    landmarks: ["八卦山脈", "八卦山大佛", "定軍山", "貓羅溪"],
    dangerLevel: 2,
    connections: ["changhua-main", "nantou-caotun"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 35, y: 47,
  },
  {
    id: "changhua-xihu",
    name: "溪湖糖廠",
    county: "彰化縣",
    element: "fire",
    terrain: "糖廠遺址",
    description: "百年糖廠改建的觀光園區，火靈能量在舊糖廠的煙囪間流動，小火車穿越甘蔗田。",
    landmarks: ["溪湖糖廠", "溪湖老街", "溪湖羊肉", "二林農業"],
    dangerLevel: 1,
    connections: ["changhua-lukang", "changhua-yuanlin"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 32, y: 48,
  },

  // ════════════════════════════════════════
  // 南投縣（10 節點）
  // ════════════════════════════════════════
  {
    id: "nantou-caotun",
    name: "草屯工藝",
    county: "南投縣",
    element: "earth",
    terrain: "工藝城鎮",
    description: "台灣工藝研究發展中心所在地，土靈能量在陶瓷與竹編工藝間凝聚。",
    landmarks: ["台灣工藝研究發展中心", "草屯老街", "草屯公園", "烏溪"],
    dangerLevel: 1,
    connections: ["taichung-wufeng", "changhua-main", "nantou-main"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 37, y: 47,
  },
  {
    id: "nantou-main",
    name: "南投市區",
    county: "南投縣",
    element: "earth",
    terrain: "山城市區",
    description: "台灣唯一不靠海的縣城，土靈能量深厚，是通往中央山脈的重要門戶。",
    landmarks: ["南投縣政府", "南投酒廠", "鳳凰山", "南投老街"],
    dangerLevel: 2,
    connections: ["nantou-caotun", "nantou-jiji", "nantou-puli"],
    travelTime: 35,
    monsterLevel: [3, 8],
    x: 38, y: 48,
  },
  {
    id: "nantou-jiji",
    name: "集集小鎮",
    county: "南投縣",
    element: "wood",
    terrain: "鐵道小鎮",
    description: "集集支線終點站，木靈能量在綠色隧道的樟樹間流動，武昌宮見證921大地震的奇蹟。",
    landmarks: ["集集車站", "綠色隧道", "武昌宮", "集集攔河堰"],
    dangerLevel: 2,
    connections: ["changhua-ershui", "nantou-main", "nantou-shuili"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 37, y: 50,
  },
  {
    id: "nantou-shuili",
    name: "水里蛇窯",
    county: "南投縣",
    element: "fire",
    terrain: "陶瓷山城",
    description: "百年蛇窯的故鄉，火靈能量在窯火中凝聚，陶藝師的技藝代代相傳。",
    landmarks: ["水里蛇窯", "水里老街", "水里車站", "陳源興陶藝"],
    dangerLevel: 2,
    connections: ["nantou-jiji", "nantou-yuchi"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 38, y: 51,
  },
  {
    id: "nantou-yuchi",
    name: "魚池日月潭",
    county: "南投縣",
    element: "water",
    terrain: "高山湖泊",
    description: "台灣最美的高山湖泊，水靈在湖面上起舞，邵族的傳說在月光下訴說著古老的秘密。",
    landmarks: ["日月潭", "文武廟", "玄光寺", "向山遊客中心"],
    dangerLevel: 3,
    connections: ["nantou-shuili", "nantou-renai", "nantou-puli"],
    travelTime: 55,
    monsterLevel: [6, 15],
    x: 39, y: 51,
  },
  {
    id: "nantou-puli",
    name: "埔里紹興",
    county: "南投縣",
    element: "water",
    terrain: "盆地小鎮",
    description: "台灣地理中心，水靈能量在埔里盆地的清泉中流動，紹興酒廠的香氣飄散四方。",
    landmarks: ["埔里紹興酒廠", "台灣地理中心碑", "埔里老街", "眉溪"],
    dangerLevel: 2,
    connections: ["nantou-main", "nantou-yuchi", "nantou-renai"],
    travelTime: 50,
    monsterLevel: [4, 11],
    x: 40, y: 49,
  },
  {
    id: "nantou-renai",
    name: "仁愛清境",
    county: "南投縣",
    element: "metal",
    terrain: "高山牧場",
    description: "台灣的小瑞士，金靈能量在高山冷冽空氣中凝聚，清境農場的綿羊是金靈獸的化身。",
    landmarks: ["清境農場", "合歡山", "奧萬大國家森林", "廬山溫泉"],
    dangerLevel: 4,
    connections: ["nantou-puli", "nantou-yuchi", "taichung-heping"],
    travelTime: 75,
    monsterLevel: [11, 22],
    x: 41, y: 47,
  },
  {
    id: "nantou-xinyi",
    name: "信義梅鄉",
    county: "南投縣",
    element: "wood",
    terrain: "山地農村",
    description: "台灣最大的梅子產地，木靈能量在梅花盛開時最為旺盛，布農族的傳統領域。",
    landmarks: ["梅子夢工廠", "信義鄉梅園", "神木村", "布農族文化"],
    dangerLevel: 3,
    connections: ["nantou-shuili", "nantou-yuchi"],
    travelTime: 65,
    monsterLevel: [7, 16],
    x: 40, y: 53,
  },
  {
    id: "nantou-lugu",
    name: "鹿谷溪頭",
    county: "南投縣",
    element: "wood",
    terrain: "竹林山區",
    description: "溪頭自然教育園區的竹林是木靈的聖地，鳳凰谷鳥園是木靈獸的天堂。",
    landmarks: ["溪頭自然教育園區", "鳳凰谷鳥園", "大學池", "鹿谷茶園"],
    dangerLevel: 3,
    connections: ["nantou-main", "nantou-jiji"],
    travelTime: 60,
    monsterLevel: [6, 15],
    x: 37, y: 51,
  },
  {
    id: "nantou-zhongliao",
    name: "中寮龍眼",
    county: "南投縣",
    element: "fire",
    terrain: "丘陵農村",
    description: "龍眼乾的故鄉，火靈能量在烘焙龍眼的煙霧中升騰，921地震後重建的農村充滿生命力。",
    landmarks: ["中寮龍眼林", "中寮老街", "安農溪", "龍眼乾工廠"],
    dangerLevel: 2,
    connections: ["nantou-caotun", "nantou-main"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 37, y: 49,
  },

  // ════════════════════════════════════════
  // 雲林縣（9 節點）
  // ════════════════════════════════════════
  {
    id: "yunlin-douliu",
    name: "斗六太平老街",
    county: "雲林縣",
    element: "earth",
    terrain: "老街城市",
    description: "雲林縣城，土靈能量在太平老街的日式建築間流動，文化路夜市是旅人的補給站。",
    landmarks: ["太平老街", "斗六火車站", "斗六文化路夜市", "雲林縣政府"],
    dangerLevel: 1,
    connections: ["yunlin-xiluo", "yunlin-gukeng", "chiayi-main"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 34, y: 52,
  },
  {
    id: "yunlin-xiluo",
    name: "西螺大橋",
    county: "雲林縣",
    element: "metal",
    terrain: "橋頭老街",
    description: "昔日遠東第一大橋，金靈能量在鋼鐵橋身間流動，西螺醬油的香氣是金靈獸的最愛。",
    landmarks: ["西螺大橋", "西螺老街", "振文書院", "西螺醬油"],
    dangerLevel: 2,
    connections: ["changhua-yuanlin", "yunlin-douliu"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 33, y: 50,
  },
  {
    id: "yunlin-gukeng",
    name: "古坑咖啡",
    county: "雲林縣",
    element: "fire",
    terrain: "山地農村",
    description: "台灣咖啡的故鄉，火靈能量在咖啡豆烘焙的香氣中升騰，荷苞山是旅人品嚐咖啡的聖地。",
    landmarks: ["荷苞山咖啡園", "古坑老街", "草嶺風景區", "雲林咖啡節"],
    dangerLevel: 2,
    connections: ["yunlin-douliu", "yunlin-linnei"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 35, y: 53,
  },
  {
    id: "yunlin-linnei",
    name: "林內茶鄉",
    county: "雲林縣",
    element: "wood",
    terrain: "溪畔農村",
    description: "濁水溪畔的農村，木靈能量在茶園間流動，林內淨水廠是台灣重要的水資源設施。",
    landmarks: ["林內淨水廠", "林內老街", "濁水溪", "林內茶園"],
    dangerLevel: 1,
    connections: ["yunlin-gukeng", "nantou-jiji"],
    travelTime: 40,
    monsterLevel: [2, 7],
    x: 35, y: 51,
  },
  {
    id: "yunlin-beigang",
    name: "北港媽祖",
    county: "雲林縣",
    element: "fire",
    terrain: "廟宇聖地",
    description: "台灣最重要的媽祖廟之一，火靈香火千年不斷，北港朝天宮是全台信眾朝聖的聖地。",
    landmarks: ["北港朝天宮", "北港老街", "北港糖廠", "北港溪"],
    dangerLevel: 2,
    connections: ["yunlin-douliu", "yunlin-tuku"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 32, y: 52,
  },
  {
    id: "yunlin-tuku",
    name: "土庫農村",
    county: "雲林縣",
    element: "earth",
    terrain: "平原農村",
    description: "雲林農業的核心地帶，土靈能量在廣闊稻田間流動，土庫順天宮是農民祈求豐收的廟宇。",
    landmarks: ["土庫順天宮", "土庫老街", "虎尾糖廠", "雲林農業"],
    dangerLevel: 1,
    connections: ["yunlin-beigang", "yunlin-huwei"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 32, y: 53,
  },
  {
    id: "yunlin-huwei",
    name: "虎尾糖廠",
    county: "雲林縣",
    element: "fire",
    terrain: "糖廠小鎮",
    description: "日治時期最大糖廠所在地，火靈能量在舊廠房的煙囪間流動，虎尾布袋戲是台灣文化瑰寶。",
    landmarks: ["虎尾糖廠", "虎尾布袋戲館", "虎尾老街", "虎尾溪"],
    dangerLevel: 1,
    connections: ["yunlin-tuku", "yunlin-douliu"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 33, y: 53,
  },
  {
    id: "yunlin-mailiao",
    name: "麥寮海岸",
    county: "雲林縣",
    element: "metal",
    terrain: "工業海岸",
    description: "台灣最大石化工業區所在地，金靈能量在龐大工廠的鋼鐵間凝聚，海岸線延伸至天際。",
    landmarks: ["六輕石化工業區", "麥寮海岸", "麥寮老街", "台西海岸"],
    dangerLevel: 3,
    connections: ["yunlin-beigang", "yunlin-tuku"],
    travelTime: 50,
    monsterLevel: [5, 13],
    x: 29, y: 52,
  },
  {
    id: "yunlin-linnei-cao",
    name: "草嶺地質",
    county: "雲林縣",
    element: "earth",
    terrain: "地質景觀",
    description: "921地震造就的堰塞湖地形，土靈能量在崩塌山壁間凝聚，是地質奇觀的見證地。",
    landmarks: ["草嶺風景區", "草嶺古道", "清水溪", "草嶺潭"],
    dangerLevel: 3,
    connections: ["yunlin-gukeng", "chiayi-alishan"],
    travelTime: 60,
    monsterLevel: [6, 14],
    x: 36, y: 54,
  },

  // ════════════════════════════════════════
  // 嘉義市（5 節點）
  // ════════════════════════════════════════
  {
    id: "chiayi-main",
    name: "嘉義火雞肉飯",
    county: "嘉義市",
    element: "fire",
    terrain: "都市商圈",
    description: "火雞肉飯的故鄉，火靈能量在爐火間跳動，嘉義城隍廟是旅人祈福的聖地。",
    landmarks: ["嘉義火車站", "城隍廟", "文化路夜市", "嘉義公園"],
    dangerLevel: 1,
    connections: ["yunlin-douliu", "chiayi-alishan", "chiayi-county", "tainan-main"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 34, y: 56,
  },
  {
    id: "chiayi-county",
    name: "嘉義縣朴子",
    county: "嘉義縣",
    element: "earth",
    terrain: "農業城鎮",
    description: "嘉義縣的農業重鎮，土靈能量在廣闊農田間流動，配天宮是旅人補充靈力的聖地。",
    landmarks: ["朴子配天宮", "朴子老街", "東石漁港", "朴子溪"],
    dangerLevel: 1,
    connections: ["chiayi-main", "chiayi-dongshi"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 32, y: 56,
  },
  {
    id: "chiayi-dongshi",
    name: "東石漁港",
    county: "嘉義縣",
    element: "water",
    terrain: "漁港海岸",
    description: "嘉義最重要的漁港，水靈在台灣海峽的漁船間穿梭，蚵仔是水靈獸最愛的食物。",
    landmarks: ["東石漁港", "東石蚵仔寮", "布袋鹽田", "好美里濕地"],
    dangerLevel: 2,
    connections: ["chiayi-county", "tainan-jiangjun"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 30, y: 57,
  },
  {
    id: "chiayi-alishan",
    name: "阿里山神木",
    county: "嘉義縣",
    element: "wood",
    terrain: "高山森林",
    description: "台灣最著名的高山景區，木靈能量在千年神木間澎湃，日出雲海是木靈王顯靈的時刻。",
    landmarks: ["阿里山神木群", "阿里山小火車", "祝山觀日平台", "奮起湖"],
    dangerLevel: 4,
    connections: ["chiayi-main", "yunlin-linnei-cao"],
    travelTime: 80,
    monsterLevel: [12, 22],
    x: 36, y: 58,
  },
  {
    id: "chiayi-budai",
    name: "布袋鹽田",
    county: "嘉義縣",
    element: "metal",
    terrain: "鹽田海岸",
    description: "台灣重要的鹽田產地，金靈能量在鹽晶中凝聚，布袋港是旅人前往澎湖的出發點。",
    landmarks: ["布袋鹽田", "布袋港", "好美里自然生態保護區", "布袋老街"],
    dangerLevel: 2,
    connections: ["chiayi-dongshi", "chiayi-county"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 29, y: 57,
  },
  {
    id: "chiayi-city-wenhua",
    name: "嘉義文化路夜市",
    county: "嘉義市",
    element: "fire",
    terrain: "夜市商圈",
    description: "嘉義最熱鬧的夜市，火靈能量在爐火與霓虹燈間跳動，火雞肉飯的香氣吸引四方旅人。",
    landmarks: ["文化路夜市", "嘉義公園", "射日塔", "嘉義市立博物館"],
    dangerLevel: 1,
    connections: ["chiayi-main", "chiayi-city-beimen"],
    travelTime: 20,
    monsterLevel: [1, 5],
    x: 34, y: 56,
  },
  {
    id: "chiayi-city-beimen",
    name: "嘉義北門驛",
    county: "嘉義市",
    element: "wood",
    terrain: "歷史車站",
    description: "阿里山小火車的起點，木靈能量在百年老檜木的香氣中飄散，是旅人前往阿里山的門戶。",
    landmarks: ["北門驛", "阿里山森林鐵路", "嘉義製材所", "嘉義舊監獄"],
    dangerLevel: 1,
    connections: ["chiayi-main", "chiayi-alishan", "chiayi-city-wenhua"],
    travelTime: 25,
    monsterLevel: [1, 5],
    x: 34, y: 55,
  },
  {
    id: "chiayi-city-lantan",
    name: "蘭潭水庫",
    county: "嘉義市",
    element: "water",
    terrain: "水庫湖泊",
    description: "嘉義市的後花園，水靈在蘭潭的碧波中沉睡，夜晚的水上燈光秀是水靈顯靈的時刻。",
    landmarks: ["蘭潭水庫", "蘭潭風景區", "嘉義大學", "蘭潭後湖"],
    dangerLevel: 2,
    connections: ["chiayi-main", "chiayi-alishan"],
    travelTime: 30,
    monsterLevel: [3, 8],
    x: 35, y: 57,
  },
  {
    id: "chiayi-county-meishan",
    name: "梅山太平雲梯",
    county: "嘉義縣",
    element: "wood",
    terrain: "高山雲霧",
    description: "台灣最長的景觀吊橋，木靈能量在雲霧繚繞的茶園間流動，太平老街是旅人歇腳的好地方。",
    landmarks: ["太平雲梯", "梅山公園", "太平老街", "梅山茶區"],
    dangerLevel: 3,
    connections: ["chiayi-alishan", "yunlin-linnei-cao"],
    travelTime: 60,
    monsterLevel: [8, 18],
    x: 37, y: 55,
  },
  {
    id: "chiayi-county-zhuqi",
    name: "竹崎親水公園",
    county: "嘉義縣",
    element: "water",
    terrain: "溪流公園",
    description: "清水溪畔的親水公園，水靈在溪石間嬉戲，竹崎是阿里山鐵路的重要中繼站。",
    landmarks: ["竹崎親水公園", "竹崎車站", "清水溪", "竹崎老街"],
    dangerLevel: 2,
    connections: ["chiayi-main", "chiayi-alishan"],
    travelTime: 40,
    monsterLevel: [4, 10],
    x: 35, y: 58,
  },
  {
    id: "chiayi-county-lucao",
    name: "鹿草農業鄉",
    county: "嘉義縣",
    element: "earth",
    terrain: "農業平原",
    description: "嘉義縣的農業重鎮，土靈能量在廣闊稻田間流動，鹿草鄉的米是旅人補充體力的聖糧。",
    landmarks: ["鹿草農業區", "鹿草鄉農會", "鹿草溪", "鹿草老街"],
    dangerLevel: 1,
    connections: ["chiayi-county", "tainan-jiangjun"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 33, y: 58,
  },

  // ════════════════════════════════════════
  // 台南市（14 節點）
  // ════════════════════════════════════════
  {
    id: "tainan-main",
    name: "台南赤崁樓",
    county: "台南市",
    element: "fire",
    terrain: "古都商圈",
    description: "台灣最古老的城市，火靈能量在四百年歷史的古蹟間燃燒，赤崁樓見證荷蘭時代的輝煌。",
    landmarks: ["赤崁樓", "安平古堡", "孔廟", "台南火車站"],
    dangerLevel: 1,
    connections: ["chiayi-main", "tainan-anping", "tainan-xinying", "tainan-guiren"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 33, y: 61,
  },
  {
    id: "tainan-anping",
    name: "安平古堡",
    county: "台南市",
    element: "water",
    terrain: "古港海岸",
    description: "台灣最古老的城堡，水靈在安平港的潮水間起伏，劍獅守護著這座古老的海港城市。",
    landmarks: ["安平古堡", "安平老街", "億載金城", "安平漁港"],
    dangerLevel: 2,
    connections: ["tainan-main", "tainan-jiangjun"],
    travelTime: 35,
    monsterLevel: [3, 9],
    x: 31, y: 61,
  },
  {
    id: "tainan-jiangjun",
    name: "將軍漁港",
    county: "台南市",
    element: "water",
    terrain: "漁港海岸",
    description: "台南最重要的漁港，水靈在漁船間穿梭，將軍溪口的候鳥是水靈獸的化身。",
    landmarks: ["將軍漁港", "馬沙溝濱海遊樂區", "七股鹽山", "台江國家公園"],
    dangerLevel: 2,
    connections: ["tainan-anping", "chiayi-dongshi", "tainan-qigu"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 30, y: 60,
  },
  {
    id: "tainan-qigu",
    name: "七股鹽山",
    county: "台南市",
    element: "metal",
    terrain: "鹽田濕地",
    description: "台灣最大的鹽田，金靈能量在鹽晶中凝聚，黑面琵鷺在鹽田濕地中覓食。",
    landmarks: ["七股鹽山", "七股鹽田", "黑面琵鷺保護區", "台江內海"],
    dangerLevel: 2,
    connections: ["tainan-jiangjun", "tainan-main"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 30, y: 61,
  },
  {
    id: "tainan-xinying",
    name: "新營糖廠",
    county: "台南市",
    element: "fire",
    terrain: "糖廠城市",
    description: "台南糖業的重鎮，火靈能量在糖廠的煙囪間燃燒，新營太子宮是旅人祈求平安的聖地。",
    landmarks: ["新營糖廠", "新營太子宮", "新營老街", "急水溪"],
    dangerLevel: 2,
    connections: ["tainan-main", "tainan-baihe", "chiayi-main"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 33, y: 59,
  },
  {
    id: "tainan-baihe",
    name: "白河蓮花",
    county: "台南市",
    element: "water",
    terrain: "蓮田農村",
    description: "台灣最大的蓮花產地，水靈能量在蓮花盛開時最為旺盛，白河水庫是水靈王的棲息地。",
    landmarks: ["白河蓮花節", "白河水庫", "關子嶺溫泉", "碧雲寺"],
    dangerLevel: 2,
    connections: ["tainan-xinying", "tainan-guiren"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 35, y: 59,
  },
  {
    id: "tainan-guiren",
    name: "歸仁仁德",
    county: "台南市",
    element: "earth",
    terrain: "平原城鎮",
    description: "台南市的衛星城鎮，土靈能量在廣闊平原間流動，歸仁老街保存著清代移民的記憶。",
    landmarks: ["歸仁老街", "仁德糖廠", "奇美博物館", "台南都會公園"],
    dangerLevel: 1,
    connections: ["tainan-main", "tainan-baihe", "kaohsiung-renwu"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 34, y: 62,
  },
  {
    id: "tainan-shanhua",
    name: "善化糖廠",
    county: "台南市",
    element: "fire",
    terrain: "農業城鎮",
    description: "台南農業的重要城鎮，火靈能量在糖廠的甜蜜香氣中升騰，善化慶安宮香火鼎盛。",
    landmarks: ["善化糖廠", "善化慶安宮", "善化老街", "曾文溪"],
    dangerLevel: 1,
    connections: ["tainan-main", "tainan-xinying"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 33, y: 60,
  },
  {
    id: "tainan-yujing",
    name: "玉井芒果",
    county: "台南市",
    element: "fire",
    terrain: "山地農村",
    description: "台灣芒果之鄉，火靈能量在金黃芒果的甜蜜香氣中升騰，玉井老街是旅人品嚐芒果冰的聖地。",
    landmarks: ["玉井老街", "芒果冰", "曾文水庫", "烏山頭水庫"],
    dangerLevel: 2,
    connections: ["tainan-main", "tainan-baihe"],
    travelTime: 50,
    monsterLevel: [3, 9],
    x: 35, y: 61,
  },
  {
    id: "tainan-zuozhen",
    name: "左鎮化石",
    county: "台南市",
    element: "earth",
    terrain: "惡地地形",
    description: "台灣惡地地形的代表，土靈能量在月世界的泥岩間凝聚，菜寮化石館珍藏著古生物的秘密。",
    landmarks: ["菜寮化石館", "左鎮月世界", "草山月世界", "二寮日出"],
    dangerLevel: 3,
    connections: ["tainan-yujing", "tainan-guiren"],
    travelTime: 55,
    monsterLevel: [6, 14],
    x: 35, y: 62,
  },
  {
    id: "tainan-dongshan",
    name: "東山咖啡",
    county: "台南市",
    element: "fire",
    terrain: "山地農村",
    description: "台南咖啡的新興產地，火靈能量在咖啡香氣中升騰，東山老街的龍眼乾是旅人的珍貴補給。",
    landmarks: ["東山咖啡公路", "東山老街", "碧軒寺", "東山龍眼"],
    dangerLevel: 2,
    connections: ["tainan-xinying", "tainan-baihe"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 34, y: 58,
  },
  {
    id: "tainan-nanxi",
    name: "南化水庫",
    county: "台南市",
    element: "water",
    terrain: "水庫山區",
    description: "台南最重要的水源地，水靈能量深厚，南化水庫的碧綠湖水是水靈王的聖地。",
    landmarks: ["南化水庫", "南化老街", "關山日落", "南化農村"],
    dangerLevel: 3,
    connections: ["tainan-yujing", "tainan-zuozhen"],
    travelTime: 60,
    monsterLevel: [6, 14],
    x: 35, y: 63,
  },
  {
    id: "tainan-yanshui",
    name: "鹽水蜂炮",
    county: "台南市",
    element: "fire",
    terrain: "廟宇老街",
    description: "元宵節蜂炮的故鄉，火靈能量在每年蜂炮時達到頂峰，月津港燈節是水火交融的奇景。",
    landmarks: ["鹽水武廟", "月津港燈節", "鹽水老街", "鹽水橋南老街"],
    dangerLevel: 2,
    connections: ["tainan-xinying", "tainan-main"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 32, y: 59,
  },
  {
    id: "tainan-taijiang",
    name: "台江國家公園",
    county: "台南市",
    element: "water",
    terrain: "濕地國家公園",
    description: "台灣第八座國家公園，水靈在廣闊的潟湖與濕地間自由遊蕩，是候鳥的天堂。",
    landmarks: ["台江國家公園", "四草野生動物保護區", "鹿耳門天后宮", "台江內海"],
    dangerLevel: 2,
    connections: ["tainan-anping", "tainan-qigu"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 30, y: 62,
  },

  // ════════════════════════════════════════
  // 高雄市（14 節點）
  // ════════════════════════════════════════
  {
    id: "kaohsiung-main",
    name: "高雄愛河",
    county: "高雄市",
    element: "water",
    terrain: "港口都市",
    description: "台灣第一大港城，水靈在愛河的波光中起舞，85大樓如燈塔般指引旅人方向。",
    landmarks: ["愛河", "高雄火車站", "六合夜市", "高雄港"],
    dangerLevel: 1,
    connections: ["kaohsiung-zuoying", "kaohsiung-sanmin", "kaohsiung-lingya", "kaohsiung-cijin"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 35, y: 67,
  },
  {
    id: "kaohsiung-zuoying",
    name: "左營蓮池潭",
    county: "高雄市",
    element: "water",
    terrain: "湖泊廟宇",
    description: "蓮池潭的龍虎塔是高雄的地標，水靈在潭中嬉戲，春秋閣見證了無數旅人的祈願。",
    landmarks: ["蓮池潭", "龍虎塔", "春秋閣", "左營舊城"],
    dangerLevel: 1,
    connections: ["kaohsiung-main", "kaohsiung-renwu", "kaohsiung-nanzi"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 34, y: 66,
  },
  {
    id: "kaohsiung-cijin",
    name: "旗津海岸",
    county: "高雄市",
    element: "water",
    terrain: "海島漁港",
    description: "高雄港口的長形半島，水靈在海峽的浪濤中翻滾，旗津老街的海鮮香氣吸引四方旅人。",
    landmarks: ["旗津海水浴場", "旗津老街", "旗後燈塔", "旗後砲台"],
    dangerLevel: 2,
    connections: ["kaohsiung-main", "kaohsiung-lingya"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 33, y: 68,
  },
  {
    id: "kaohsiung-lingya",
    name: "苓雅文化中心",
    county: "高雄市",
    element: "fire",
    terrain: "文化商業區",
    description: "高雄文化藝術的核心，火靈能量在文化中心的演出廳間燃燒，三多商圈是旅人購物的天堂。",
    landmarks: ["高雄文化中心", "三多商圈", "新光三越", "苓雅老街"],
    dangerLevel: 1,
    connections: ["kaohsiung-main", "kaohsiung-cijin", "kaohsiung-fengshan"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 35, y: 68,
  },
  {
    id: "kaohsiung-sanmin",
    name: "三民瑞豐夜市",
    county: "高雄市",
    element: "fire",
    terrain: "夜市商圈",
    description: "高雄最大夜市之一，火靈能量在攤販的爐火間跳動，熱鬧的氣氛吸引各路靈獸出沒。",
    landmarks: ["瑞豐夜市", "三民公園", "高雄市立圖書館", "建工路商圈"],
    dangerLevel: 1,
    connections: ["kaohsiung-main", "kaohsiung-zuoying"],
    travelTime: 25,
    monsterLevel: [2, 7],
    x: 35, y: 67,
  },
  {
    id: "kaohsiung-fengshan",
    name: "鳳山鳳儀書院",
    county: "高雄市",
    element: "earth",
    terrain: "古城商圈",
    description: "台灣保存最完整的書院之一，土靈能量在百年建築間流動，鳳山老街訴說清代移民的故事。",
    landmarks: ["鳳儀書院", "鳳山老街", "鳳山車站", "曹公圳"],
    dangerLevel: 1,
    connections: ["kaohsiung-lingya", "kaohsiung-dashu", "pingtung-main"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 36, y: 68,
  },
  {
    id: "kaohsiung-renwu",
    name: "仁武工業區",
    county: "高雄市",
    element: "metal",
    terrain: "工業城鎮",
    description: "高雄工業的重要城區，金靈能量在石化工廠的鋼鐵間凝聚，仁武老街保存著農業時代的記憶。",
    landmarks: ["仁武工業區", "仁武老街", "仁武糖廠", "後勁溪"],
    dangerLevel: 2,
    connections: ["kaohsiung-zuoying", "tainan-guiren"],
    travelTime: 35,
    monsterLevel: [3, 8],
    x: 35, y: 65,
  },
  {
    id: "kaohsiung-nanzi",
    name: "楠梓加工區",
    county: "高雄市",
    element: "metal",
    terrain: "加工出口區",
    description: "台灣第一個加工出口區，金靈能量在精密工廠間流動，楠梓老街保存著工業發展的記憶。",
    landmarks: ["楠梓加工出口區", "楠梓老街", "援中港濕地", "半屏山"],
    dangerLevel: 2,
    connections: ["kaohsiung-zuoying", "kaohsiung-main"],
    travelTime: 30,
    monsterLevel: [3, 8],
    x: 34, y: 65,
  },
  {
    id: "kaohsiung-dashu",
    name: "大樹舊鐵橋",
    county: "高雄市",
    element: "metal",
    terrain: "鐵橋河岸",
    description: "百年舊鐵橋橫跨高屏溪，金靈能量在鐵橋的鋼鐵間流動，龍目井是旅人補充水靈的聖地。",
    landmarks: ["舊鐵橋濕地公園", "龍目井", "大樹老街", "高屏溪"],
    dangerLevel: 2,
    connections: ["kaohsiung-fengshan", "kaohsiung-liugui"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 36, y: 69,
  },
  {
    id: "kaohsiung-liugui",
    name: "六龜溫泉",
    county: "高雄市",
    element: "fire",
    terrain: "山地溫泉",
    description: "荖濃溪畔的溫泉鄉，火靈能量在溫泉蒸氣中升騰，六龜神木群是木靈王的聖地。",
    landmarks: ["六龜溫泉", "六龜神木", "荖濃溪", "寶來溫泉"],
    dangerLevel: 3,
    connections: ["kaohsiung-dashu", "kaohsiung-maolin"],
    travelTime: 65,
    monsterLevel: [7, 16],
    x: 37, y: 70,
  },
  {
    id: "kaohsiung-maolin",
    name: "茂林紫蝶",
    county: "高雄市",
    element: "wood",
    terrain: "山地部落",
    description: "紫斑蝶越冬的聖地，木靈能量在蝴蝶谷的紫色花海間流動，魯凱族的傳統領域。",
    landmarks: ["茂林國家風景區", "紫蝶幽谷", "多納溫泉", "魯凱族文化"],
    dangerLevel: 4,
    connections: ["kaohsiung-liugui", "pingtung-sandimen"],
    travelTime: 80,
    monsterLevel: [11, 22],
    x: 37, y: 72,
  },
  {
    id: "kaohsiung-qishan",
    name: "旗山老街",
    county: "高雄市",
    element: "earth",
    terrain: "香蕉山城",
    description: "台灣香蕉王國的首都，土靈能量在香蕉田間流動，旗山老街的巴洛克建築是土靈精靈的家。",
    landmarks: ["旗山老街", "旗山車站", "旗山石拱橋", "旗山糖廠"],
    dangerLevel: 2,
    connections: ["kaohsiung-main", "kaohsiung-meinong"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 36, y: 68,
  },
  {
    id: "kaohsiung-meinong",
    name: "美濃客家",
    county: "高雄市",
    element: "earth",
    terrain: "客家農村",
    description: "高雄最重要的客家聚落，土靈能量在油紙傘的彩繪間流動，美濃湖是水靈精靈的棲息地。",
    landmarks: ["美濃客家文物館", "美濃湖", "油紙傘", "美濃老街"],
    dangerLevel: 2,
    connections: ["kaohsiung-qishan", "kaohsiung-liugui"],
    travelTime: 50,
    monsterLevel: [3, 9],
    x: 37, y: 69,
  },
  {
    id: "kaohsiung-xiaogang",
    name: "小港鋼鐵",
    county: "高雄市",
    element: "metal",
    terrain: "重工業港區",
    description: "台灣最大的鋼鐵工業區，金靈能量在高爐的鋼鐵間凝聚，小港機場是旅人往返的門戶。",
    landmarks: ["中鋼公司", "小港機場", "小港老街", "高雄港"],
    dangerLevel: 2,
    connections: ["kaohsiung-main", "kaohsiung-cijin", "pingtung-main"],
    travelTime: 35,
    monsterLevel: [3, 9],
    x: 34, y: 69,
  },

  // ════════════════════════════════════════
  // 屏東縣（10 節點）
  // ════════════════════════════════════════
  {
    id: "pingtung-main",
    name: "屏東市區",
    county: "屏東縣",
    element: "fire",
    terrain: "都市商圈",
    description: "台灣最南端的縣城，火靈能量在熱帶陽光下燃燒，屏東夜市的熱鬧氣氛吸引靈獸聚集。",
    landmarks: ["屏東火車站", "屏東夜市", "屏東縣政府", "勝利星村"],
    dangerLevel: 1,
    connections: ["kaohsiung-fengshan", "kaohsiung-xiaogang", "pingtung-chaozhou", "pingtung-sandimen"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 37, y: 70,
  },
  {
    id: "pingtung-chaozhou",
    name: "潮州老街",
    county: "屏東縣",
    element: "earth",
    terrain: "農業城鎮",
    description: "屏東農業的重要城鎮，土靈能量在廣闊農田間流動，潮州老街保存著客家移民的記憶。",
    landmarks: ["潮州老街", "潮州車站", "潮州公園", "東港溪"],
    dangerLevel: 1,
    connections: ["pingtung-main", "pingtung-donggang", "pingtung-fangliao"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 37, y: 71,
  },
  {
    id: "pingtung-donggang",
    name: "東港黑鮪魚",
    county: "屏東縣",
    element: "water",
    terrain: "漁港海岸",
    description: "台灣黑鮪魚的故鄉，水靈在深海中追逐黑鮪魚，東港三寶（黑鮪魚、油魚子、櫻花蝦）是旅人的珍貴補給。",
    landmarks: ["東港漁港", "東隆宮", "東港老街", "大鵬灣"],
    dangerLevel: 2,
    connections: ["pingtung-chaozhou", "pingtung-liuqiu"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 35, y: 72,
  },
  {
    id: "pingtung-liuqiu",
    name: "小琉球珊瑚",
    county: "屏東縣",
    element: "water",
    terrain: "珊瑚礁島",
    description: "台灣唯一的珊瑚礁島，水靈在清澈的珊瑚礁間嬉戲，海龜是水靈王的使者。",
    landmarks: ["小琉球", "花瓶岩", "美人洞", "厚石群礁"],
    dangerLevel: 3,
    connections: ["pingtung-donggang"],
    travelTime: 60,
    monsterLevel: [6, 15],
    x: 33, y: 73,
  },
  {
    id: "pingtung-sandimen",
    name: "三地門原住民",
    county: "屏東縣",
    element: "wood",
    terrain: "山地部落",
    description: "排灣族的傳統聚落，木靈能量在百步蛇的圖騰間流動，地磨兒公園是旅人了解原住民文化的窗口。",
    landmarks: ["地磨兒公園", "三地門老街", "排灣族文化", "隘寮溪"],
    dangerLevel: 3,
    connections: ["pingtung-main", "kaohsiung-maolin", "pingtung-wutai"],
    travelTime: 55,
    monsterLevel: [6, 15],
    x: 37, y: 71,
  },
  {
    id: "pingtung-wutai",
    name: "霧台魯凱",
    county: "屏東縣",
    element: "earth",
    terrain: "高山部落",
    description: "魯凱族的神聖山地，土靈能量在石板屋的古老建築間凝聚，好茶舊部落是世界文化遺產候選地。",
    landmarks: ["霧台石板屋", "魯凱族文化", "好茶舊部落", "霧台部落"],
    dangerLevel: 4,
    connections: ["pingtung-sandimen", "pingtung-majia"],
    travelTime: 75,
    monsterLevel: [11, 22],
    x: 38, y: 72,
  },
  {
    id: "pingtung-majia",
    name: "瑪家原住民",
    county: "屏東縣",
    element: "wood",
    terrain: "山地部落",
    description: "原住民族文化園區所在地，木靈能量在原住民傳統建築間流動，是了解台灣原住民文化的最佳地點。",
    landmarks: ["台灣原住民族文化園區", "瑪家農場", "北葉部落", "隘寮北溪"],
    dangerLevel: 3,
    connections: ["pingtung-sandimen", "pingtung-wutai"],
    travelTime: 60,
    monsterLevel: [7, 16],
    x: 37, y: 72,
  },
  {
    id: "pingtung-fangliao",
    name: "枋寮海岸",
    county: "屏東縣",
    element: "water",
    terrain: "海岸漁村",
    description: "台灣西海岸的最南端，水靈在台灣海峽與巴士海峽的交界處起舞，枋寮漁港的夕陽是旅人最美的記憶。",
    landmarks: ["枋寮漁港", "枋寮老街", "F3藝術特區", "枋寮車站"],
    dangerLevel: 2,
    connections: ["pingtung-chaozhou", "pingtung-hengchun"],
    travelTime: 50,
    monsterLevel: [3, 9],
    x: 36, y: 73,
  },
  {
    id: "pingtung-hengchun",
    name: "恆春古城",
    county: "屏東縣",
    element: "fire",
    terrain: "古城海岸",
    description: "台灣保存最完整的古城牆，火靈能量在熱帶陽光下最為旺盛，落山風是火靈能量的具體展現。",
    landmarks: ["恆春古城", "墾丁國家公園", "南灣", "出火特別景觀區"],
    dangerLevel: 3,
    connections: ["pingtung-fangliao", "pingtung-kenting"],
    travelTime: 60,
    monsterLevel: [6, 15],
    x: 37, y: 75,
  },
  {
    id: "pingtung-kenting",
    name: "墾丁國家公園",
    county: "屏東縣",
    element: "water",
    terrain: "熱帶海岸",
    description: "台灣最南端的國家公園，水靈在珊瑚礁海岸的清澈海水中自由遊蕩，是全台水靈能量最旺盛的地方。",
    landmarks: ["墾丁大街", "鵝鑾鼻燈塔", "龍磐公園", "貓鼻頭"],
    dangerLevel: 4,
    connections: ["pingtung-hengchun"],
    travelTime: 70,
    monsterLevel: [11, 22],
    x: 37, y: 77,
  },

  // ════════════════════════════════════════
  // 宜蘭縣（9 節點）
  // ════════════════════════════════════════
  {
    id: "yilan-luodong",
    name: "羅東夜市",
    county: "宜蘭縣",
    element: "wood",
    terrain: "山城夜市",
    description: "宜蘭最熱鬧的夜市，木靈能量在林業文化園區的老樹間流動，羅東林業文化園區訴說著百年伐木史。",
    landmarks: ["羅東夜市", "羅東林業文化園區", "羅東運動公園", "中山公園"],
    dangerLevel: 1,
    connections: ["yilan-main", "yilan-dongshan", "yilan-jiaoxi"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 63, y: 28,
  },
  {
    id: "yilan-main",
    name: "宜蘭市區",
    county: "宜蘭縣",
    element: "water",
    terrain: "平原城市",
    description: "蘭陽平原的中心，水靈能量在宜蘭河的清流中流動，宜蘭傳藝中心是旅人了解台灣傳統文化的窗口。",
    landmarks: ["宜蘭傳藝中心", "宜蘭火車站", "宜蘭縣政府", "宜蘭河"],
    dangerLevel: 1,
    connections: ["yilan-luodong", "yilan-jiaoxi", "yilan-toucheng"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 62, y: 26,
  },
  {
    id: "yilan-jiaoxi",
    name: "礁溪溫泉",
    county: "宜蘭縣",
    element: "water",
    terrain: "溫泉小鎮",
    description: "台灣唯一的平地溫泉，水靈能量在溫泉蒸氣中升騰，礁溪老街的溫泉湯圓是旅人的珍貴補給。",
    landmarks: ["礁溪溫泉", "礁溪老街", "五峰旗瀑布", "礁溪車站"],
    dangerLevel: 1,
    connections: ["yilan-main", "yilan-toucheng", "nb-pinglin"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 61, y: 24,
  },
  {
    id: "yilan-toucheng",
    name: "頭城老街",
    county: "宜蘭縣",
    element: "earth",
    terrain: "海岸老街",
    description: "宜蘭最古老的城鎮，土靈能量在百年老街的磚牆間流動，龜山島在海面上神秘地守護著蘭陽平原。",
    landmarks: ["頭城老街", "烏石港", "龜山島", "蘭陽博物館"],
    dangerLevel: 2,
    connections: ["yilan-jiaoxi", "yilan-main", "nb-pinglin"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 61, y: 22,
  },
  {
    id: "yilan-dongshan",
    name: "冬山河",
    county: "宜蘭縣",
    element: "water",
    terrain: "河岸農村",
    description: "冬山河親水公園是水靈的樂園，水靈在河面上起舞，國際童玩節是全台最歡樂的水靈慶典。",
    landmarks: ["冬山河親水公園", "國際童玩節", "冬山老街", "仁山植物園"],
    dangerLevel: 1,
    connections: ["yilan-luodong", "yilan-suao"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 63, y: 29,
  },
  {
    id: "yilan-suao",
    name: "蘇澳冷泉",
    county: "宜蘭縣",
    element: "water",
    terrain: "漁港冷泉",
    description: "全台唯一的碳酸冷泉，水靈能量在冰涼的泉水中凝聚，蘇澳漁港的海鮮是旅人補充體力的最佳選擇。",
    landmarks: ["蘇澳冷泉", "蘇澳漁港", "南方澳漁港", "蘇花公路起點"],
    dangerLevel: 2,
    connections: ["yilan-dongshan", "hualien-xiulin"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 64, y: 31,
  },
  {
    id: "yilan-datong",
    name: "大同太平山",
    county: "宜蘭縣",
    element: "wood",
    terrain: "高山森林",
    description: "太平山國家森林遊樂區的原始森林，木靈能量在千年神木間澎湃，翠峰湖是木靈王的聖地。",
    landmarks: ["太平山國家森林遊樂區", "翠峰湖", "見晴懷古步道", "鐵杉林"],
    dangerLevel: 4,
    connections: ["yilan-luodong", "yilan-nanao"],
    travelTime: 80,
    monsterLevel: [11, 22],
    x: 62, y: 30,
  },
  {
    id: "yilan-nanao",
    name: "南澳原野",
    county: "宜蘭縣",
    element: "wood",
    terrain: "山地部落",
    description: "泰雅族的傳統領域，木靈能量在原始山林中澎湃，南澳古道是旅人探索秘境的冒險路線。",
    landmarks: ["南澳古道", "朝陽國家步道", "南澳漁港", "泰雅族文化"],
    dangerLevel: 3,
    connections: ["yilan-suao", "yilan-datong"],
    travelTime: 65,
    monsterLevel: [7, 16],
    x: 64, y: 33,
  },
  {
    id: "yilan-yuanshan",
    name: "員山水鄉",
    county: "宜蘭縣",
    element: "water",
    terrain: "湖泊農村",
    description: "宜蘭最美的農村景觀，水靈在員山鄉的湖泊間嬉戲，望龍埤是旅人休憩的秘境。",
    landmarks: ["望龍埤", "員山公園", "員山酒廠", "蘭陽溪"],
    dangerLevel: 1,
    connections: ["yilan-main", "yilan-luodong"],
    travelTime: 30,
    monsterLevel: [2, 7],
    x: 62, y: 27,
  },

  // ════════════════════════════════════════
  // 花蓮縣（10 節點）
  // ════════════════════════════════════════
  {
    id: "hualien-main",
    name: "花蓮市區",
    county: "花蓮縣",
    element: "earth",
    terrain: "海岸城市",
    description: "後山的首府，土靈能量在太魯閣的大理石間凝聚，花蓮港的夕陽是旅人最美的記憶。",
    landmarks: ["花蓮火車站", "花蓮港", "松園別館", "花蓮文創園區"],
    dangerLevel: 2,
    connections: ["hualien-xiulin", "hualien-xincheng", "hualien-fuyuan"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 67, y: 37,
  },
  {
    id: "hualien-xiulin",
    name: "太魯閣峽谷",
    county: "花蓮縣",
    element: "earth",
    terrain: "峽谷地形",
    description: "台灣最壯觀的峽谷，土靈能量在大理石峭壁間凝聚，立霧溪的清流是旅人淨化靈魂的聖地。",
    landmarks: ["太魯閣國家公園", "燕子口", "九曲洞", "天祥"],
    dangerLevel: 4,
    connections: ["hualien-main", "hualien-xincheng", "yilan-suao"],
    travelTime: 60,
    monsterLevel: [11, 22],
    x: 66, y: 34,
  },
  {
    id: "hualien-xincheng",
    name: "新城七星潭",
    county: "花蓮縣",
    element: "water",
    terrain: "礫石海岸",
    description: "七星潭的礫石海岸，水靈在太平洋的浪濤中翻滾，清水斷崖是台灣最壯觀的海岸地形。",
    landmarks: ["七星潭", "清水斷崖", "新城老街", "花蓮機場"],
    dangerLevel: 2,
    connections: ["hualien-main", "hualien-xiulin"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 67, y: 35,
  },
  {
    id: "hualien-fuyuan",
    name: "鯉魚潭",
    county: "花蓮縣",
    element: "water",
    terrain: "湖泊山區",
    description: "花蓮最大的內陸湖，水靈在湖面上起舞，鯉魚山步道是旅人親近自然的好地方。",
    landmarks: ["鯉魚潭", "鯉魚山步道", "壽豐老街", "花蓮溪"],
    dangerLevel: 2,
    connections: ["hualien-main", "hualien-guangfu"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 67, y: 40,
  },
  {
    id: "hualien-guangfu",
    name: "光復糖廠",
    county: "花蓮縣",
    element: "fire",
    terrain: "糖廠農村",
    description: "花蓮糖廠改建的觀光園區，火靈能量在舊廠房的煙囪間流動，阿美族文化村是旅人了解原住民文化的窗口。",
    landmarks: ["光復糖廠", "阿美族文化村", "馬太鞍濕地", "光復老街"],
    dangerLevel: 2,
    connections: ["hualien-fuyuan", "hualien-ruisui"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 67, y: 43,
  },
  {
    id: "hualien-ruisui",
    name: "瑞穗溫泉",
    county: "花蓮縣",
    element: "water",
    terrain: "溫泉農村",
    description: "秀姑巒溪畔的溫泉鄉，水靈能量在溫泉蒸氣中升騰，泛舟是旅人體驗水靈能量的最佳方式。",
    landmarks: ["瑞穗溫泉", "秀姑巒溪泛舟", "瑞穗牧場", "奇美部落"],
    dangerLevel: 2,
    connections: ["hualien-guangfu", "hualien-yuli"],
    travelTime: 50,
    monsterLevel: [3, 9],
    x: 67, y: 46,
  },
  {
    id: "hualien-yuli",
    name: "玉里溫泉",
    county: "花蓮縣",
    element: "fire",
    terrain: "山城溫泉",
    description: "花蓮南部的重要城鎮，火靈能量在溫泉蒸氣中升騰，玉里橋下的秀姑巒溪是水靈的棲息地。",
    landmarks: ["玉里溫泉", "玉里老街", "玉里車站", "秀姑巒溪"],
    dangerLevel: 2,
    connections: ["hualien-ruisui", "hualien-fuli"],
    travelTime: 50,
    monsterLevel: [3, 9],
    x: 67, y: 50,
  },
  {
    id: "hualien-fuli",
    name: "富里六十石山",
    county: "花蓮縣",
    element: "wood",
    terrain: "高山農業",
    description: "六十石山的金針花海是木靈能量最旺盛的地方，富里有機農業是旅人補充木靈的聖地。",
    landmarks: ["六十石山", "金針花海", "富里老街", "羅山瀑布"],
    dangerLevel: 3,
    connections: ["hualien-yuli", "taitung-chishang"],
    travelTime: 60,
    monsterLevel: [6, 15],
    x: 67, y: 53,
  },
  {
    id: "hualien-shoufeng",
    name: "壽豐理想大地",
    county: "花蓮縣",
    element: "earth",
    terrain: "農村平原",
    description: "花蓮溪出海口的農村，土靈能量在廣闊農田間流動，理想大地渡假村是旅人休憩的天堂。",
    landmarks: ["理想大地渡假村", "壽豐老街", "花蓮溪出海口", "壽豐車站"],
    dangerLevel: 1,
    connections: ["hualien-main", "hualien-fuyuan"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 67, y: 38,
  },
  {
    id: "hualien-fengbin",
    name: "豐濱石梯坪",
    county: "花蓮縣",
    element: "water",
    terrain: "海岸地質",
    description: "東海岸最美的地質景觀，水靈在壺穴地形的岩石間嬉戲，石梯坪是旅人觀賞日出的聖地。",
    landmarks: ["石梯坪", "石梯漁港", "磯崎海水浴場", "阿美族文化"],
    dangerLevel: 3,
    connections: ["hualien-guangfu", "taitung-chenggong"],
    travelTime: 65,
    monsterLevel: [6, 15],
    x: 69, y: 46,
  },

  // ════════════════════════════════════════
  // 台東縣（10 節點）
  // ════════════════════════════════════════
  {
    id: "taitung-main",
    name: "台東市區",
    county: "台東縣",
    element: "fire",
    terrain: "海岸城市",
    description: "後山的南方首府，火靈能量在熱帶陽光下燃燒，台東鐵花村的音樂是火靈能量的具體展現。",
    landmarks: ["台東火車站", "鐵花村", "台東森林公園", "台東市區"],
    dangerLevel: 2,
    connections: ["taitung-beinan", "taitung-chenggong", "taitung-luye"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 68, y: 60,
  },
  {
    id: "taitung-beinan",
    name: "卑南文化遺址",
    county: "台東縣",
    element: "earth",
    terrain: "史前遺址",
    description: "台灣最重要的史前遺址，土靈能量在千年石棺間凝聚，卑南族的傳統領域充滿古老的靈氣。",
    landmarks: ["卑南文化公園", "台東史前博物館", "知本溫泉", "南王部落"],
    dangerLevel: 2,
    connections: ["taitung-main", "taitung-taimali"],
    travelTime: 40,
    monsterLevel: [3, 9],
    x: 68, y: 62,
  },
  {
    id: "taitung-chenggong",
    name: "成功漁港",
    county: "台東縣",
    element: "water",
    terrain: "漁港海岸",
    description: "台東最重要的漁港，水靈在太平洋的深海中追逐旗魚，三仙台是水靈王的聖地。",
    landmarks: ["成功漁港", "三仙台", "八仙洞", "小野柳"],
    dangerLevel: 3,
    connections: ["taitung-main", "hualien-fengbin"],
    travelTime: 60,
    monsterLevel: [6, 15],
    x: 69, y: 56,
  },
  {
    id: "taitung-luye",
    name: "鹿野高台",
    county: "台東縣",
    element: "wood",
    terrain: "高台農業",
    description: "台灣熱氣球嘉年華的舉辦地，木靈能量在茶園的綠意中流動，高台上的視野讓旅人心曠神怡。",
    landmarks: ["鹿野高台", "熱氣球嘉年華", "鹿野茶園", "龍田村"],
    dangerLevel: 2,
    connections: ["taitung-main", "taitung-chishang"],
    travelTime: 45,
    monsterLevel: [3, 9],
    x: 67, y: 57,
  },
  {
    id: "taitung-chishang",
    name: "池上伯朗大道",
    county: "台東縣",
    element: "earth",
    terrain: "稻田平原",
    description: "台灣最美的稻田景觀，土靈能量在金黃稻田間流動，伯朗大道是旅人感受大地能量的聖地。",
    landmarks: ["伯朗大道", "池上便當", "大坡池", "天堂路"],
    dangerLevel: 2,
    connections: ["taitung-luye", "hualien-fuli"],
    travelTime: 50,
    monsterLevel: [3, 9],
    x: 67, y: 55,
  },
  {
    id: "taitung-taimali",
    name: "太麻里金針山",
    county: "台東縣",
    element: "wood",
    terrain: "海岸山地",
    description: "台灣迎接第一道曙光的地方，木靈能量在金針花海間流動，太麻里溪是旅人淨化靈魂的聖地。",
    landmarks: ["太麻里金針山", "第一道曙光", "太麻里溪", "金崙溫泉"],
    dangerLevel: 3,
    connections: ["taitung-beinan", "taitung-dawu"],
    travelTime: 60,
    monsterLevel: [6, 15],
    x: 68, y: 65,
  },
  {
    id: "taitung-dawu",
    name: "大武海岸",
    county: "台東縣",
    element: "water",
    terrain: "海岸山地",
    description: "台東最南端的城鎮，水靈在太平洋的浪濤中翻滾，大武山是排灣族的聖山。",
    landmarks: ["大武漁港", "大武老街", "大武山", "大鳥部落"],
    dangerLevel: 3,
    connections: ["taitung-taimali", "pingtung-hengchun"],
    travelTime: 70,
    monsterLevel: [7, 16],
    x: 68, y: 68,
  },
  {
    id: "taitung-lanyu",
    name: "蘭嶼達悟族",
    county: "台東縣",
    element: "water",
    terrain: "火山島嶼",
    description: "達悟族的聖島，水靈在太平洋的深藍海水中自由遊蕩，飛魚是水靈王的使者。",
    landmarks: ["蘭嶼", "達悟族文化", "飛魚季", "朗島部落"],
    dangerLevel: 4,
    connections: ["taitung-main"],
    travelTime: 90,
    monsterLevel: [11, 22],
    x: 73, y: 68,
  },
  {
    id: "taitung-lyudao",
    name: "綠島珊瑚礁",
    county: "台東縣",
    element: "water",
    terrain: "火山島嶼",
    description: "台灣最美的珊瑚礁潛水地，水靈在清澈的海水中自由遊蕩，綠島燈塔是旅人的指引。",
    landmarks: ["綠島燈塔", "朝日溫泉", "柚子湖", "綠島監獄"],
    dangerLevel: 3,
    connections: ["taitung-main"],
    travelTime: 75,
    monsterLevel: [7, 16],
    x: 71, y: 64,
  },
  {
    id: "taitung-yanping",
    name: "延平布農族",
    county: "台東縣",
    element: "wood",
    terrain: "山地部落",
    description: "布農族的傳統領域，木靈能量在原始山林中澎湃，八部合音是木靈能量的音樂展現。",
    landmarks: ["延平布農族部落", "鸞山森林博物館", "新武呂溪", "布農族文化"],
    dangerLevel: 3,
    connections: ["taitung-luye", "taitung-chishang"],
    travelTime: 65,
    monsterLevel: [7, 16],
    x: 66, y: 58,
  },

  // ════════════════════════════════════════
  // 澎湖縣（6 節點）
  // ════════════════════════════════════════
  {
    id: "penghu-main",
    name: "馬公天后宮",
    county: "澎湖縣",
    element: "water",
    terrain: "海島城市",
    description: "台灣最古老的媽祖廟，水靈能量在澎湖的海風中最為旺盛，菊島的玄武岩地形是水靈王的傑作。",
    landmarks: ["澎湖天后宮", "馬公老街", "中央老街", "澎湖港"],
    dangerLevel: 2,
    connections: ["penghu-xiyu", "penghu-baisha", "penghu-qimei"],
    travelTime: 50,
    monsterLevel: [4, 11],
    x: 22, y: 58,
  },
  {
    id: "penghu-xiyu",
    name: "西嶼燈塔",
    county: "澎湖縣",
    element: "metal",
    terrain: "海島燈塔",
    description: "台灣最古老的燈塔，金靈能量在燈塔的鐵鑄結構間凝聚，西嶼的夕陽是旅人最美的記憶。",
    landmarks: ["西嶼燈塔", "通梁古榕", "二崁聚落", "大菓葉玄武岩"],
    dangerLevel: 3,
    connections: ["penghu-main"],
    travelTime: 55,
    monsterLevel: [5, 13],
    x: 20, y: 57,
  },
  {
    id: "penghu-baisha",
    name: "白沙跨海大橋",
    county: "澎湖縣",
    element: "metal",
    terrain: "海島橋梁",
    description: "澎湖跨海大橋橫跨海峽，金靈能量在橋梁的鋼鐵間流動，吉貝島的沙灘是水靈精靈的樂園。",
    landmarks: ["澎湖跨海大橋", "吉貝島", "白沙老街", "赤崁村"],
    dangerLevel: 3,
    connections: ["penghu-main"],
    travelTime: 55,
    monsterLevel: [5, 13],
    x: 22, y: 56,
  },
  {
    id: "penghu-qimei",
    name: "七美雙心石滬",
    county: "澎湖縣",
    element: "water",
    terrain: "南島海岸",
    description: "澎湖最南端的島嶼，水靈在雙心石滬的潮汐間起伏，七美嶼的玄武岩地形是水靈王的傑作。",
    landmarks: ["七美雙心石滬", "七美嶼", "大獅石", "七美人塚"],
    dangerLevel: 3,
    connections: ["penghu-main"],
    travelTime: 65,
    monsterLevel: [6, 14],
    x: 21, y: 61,
  },
  {
    id: "penghu-wangan",
    name: "望安花宅",
    county: "澎湖縣",
    element: "earth",
    terrain: "古聚落島嶼",
    description: "保存最完好的澎湖傳統聚落，土靈能量在百年咕咾石牆間凝聚，綠蠵龜在沙灘上產卵。",
    landmarks: ["花宅聚落", "望安島", "綠蠵龜保護區", "天台山"],
    dangerLevel: 3,
    connections: ["penghu-main", "penghu-qimei"],
    travelTime: 60,
    monsterLevel: [5, 13],
    x: 22, y: 60,
  },
  {
    id: "penghu-huayu",
    name: "花嶼鳥島",
    county: "澎湖縣",
    element: "wood",
    terrain: "無人島嶼",
    description: "澎湖最偏遠的島嶼，木靈能量在海鳥的鳴叫聲中流動，是旅人探索秘境的終極挑戰。",
    landmarks: ["花嶼", "海鳥棲地", "玄武岩地形", "澎湖最西端"],
    dangerLevel: 4,
    connections: ["penghu-wangan"],
    travelTime: 90,
    monsterLevel: [11, 22],
    x: 18, y: 60,
  },

  // ════════════════════════════════════════
  // 金門縣（5 節點）
  // ════════════════════════════════════════
  {
    id: "kinmen-main",
    name: "金城老街",
    county: "金門縣",
    element: "metal",
    terrain: "古城老街",
    description: "金門最重要的城鎮，金靈能量在砲彈鋼刀的鐵器間凝聚，莒光樓見證了金門的歷史。",
    landmarks: ["莒光樓", "金城老街", "金門縣政府", "金門機場"],
    dangerLevel: 2,
    connections: ["kinmen-jinhu", "kinmen-lieyu"],
    travelTime: 50,
    monsterLevel: [4, 11],
    x: 12, y: 52,
  },
  {
    id: "kinmen-jinhu",
    name: "金湖太湖",
    county: "金門縣",
    element: "water",
    terrain: "湖泊城鎮",
    description: "金門最大的湖泊，水靈在太湖的清水中嬉戲，山外老街是旅人補充體力的好地方。",
    landmarks: ["太湖", "山外老街", "金湖鎮公所", "成功水庫"],
    dangerLevel: 2,
    connections: ["kinmen-main", "kinmen-jinsha"],
    travelTime: 45,
    monsterLevel: [4, 11],
    x: 14, y: 51,
  },
  {
    id: "kinmen-jinsha",
    name: "金沙古寧頭",
    county: "金門縣",
    element: "earth",
    terrain: "古戰場海岸",
    description: "古寧頭戰役的歷史戰場，土靈能量在砲彈坑的土地間凝聚，北山古洋樓訴說著戰爭的記憶。",
    landmarks: ["古寧頭戰史館", "北山古洋樓", "湖井頭戰史館", "金沙老街"],
    dangerLevel: 3,
    connections: ["kinmen-jinhu", "kinmen-main"],
    travelTime: 50,
    monsterLevel: [5, 13],
    x: 13, y: 50,
  },
  {
    id: "kinmen-lieyu",
    name: "烈嶼小金門",
    county: "金門縣",
    element: "metal",
    terrain: "離島要塞",
    description: "小金門的軍事要塞，金靈能量在廢棄碉堡的鋼鐵間凝聚，八達樓子是旅人探索秘境的終極挑戰。",
    landmarks: ["八達樓子", "烈嶼鄉公所", "湖下海水浴場", "小金門"],
    dangerLevel: 3,
    connections: ["kinmen-main"],
    travelTime: 60,
    monsterLevel: [5, 13],
    x: 11, y: 53,
  },
  {
    id: "kinmen-jinning",
    name: "金寧瓊林",
    county: "金門縣",
    element: "earth",
    terrain: "聚落村莊",
    description: "金門保存最完整的傳統聚落，土靈能量在百年閩南建築的紅磚間凝聚，瓊林蔡氏宗祠是土靈的聖地。",
    landmarks: ["瓊林聚落", "瓊林蔡氏宗祠", "金門民俗文化村", "水頭聚落"],
    dangerLevel: 2,
    connections: ["kinmen-main", "kinmen-jinhu"],
    travelTime: 45,
    monsterLevel: [3, 10],
    x: 12, y: 52,
  },

  // ════════════════════════════════════════
  // 連江縣（馬祖）（5 節點）
  // ════════════════════════════════════════
  {
    id: "matsu-nangan",
    name: "南竿介壽村",
    county: "連江縣",
    element: "water",
    terrain: "海島城鎮",
    description: "馬祖最大的島嶼，水靈在馬祖列島的藍眼淚海水中閃爍，北海坑道是旅人探索秘境的終極挑戰。",
    landmarks: ["北海坑道", "介壽村", "馬祖機場", "津沙聚落"],
    dangerLevel: 3,
    connections: ["matsu-beigan", "matsu-dongyin"],
    travelTime: 70,
    monsterLevel: [6, 15],
    x: 8, y: 40,
  },
  {
    id: "matsu-beigan",
    name: "北竿塘岐",
    county: "連江縣",
    element: "water",
    terrain: "海島漁村",
    description: "馬祖第二大島，水靈在芹壁聚落的海灣間嬉戲，北竿機場的海景是旅人最美的記憶。",
    landmarks: ["芹壁聚落", "塘岐老街", "北竿機場", "壁山"],
    dangerLevel: 3,
    connections: ["matsu-nangan"],
    travelTime: 65,
    monsterLevel: [6, 15],
    x: 8, y: 38,
  },
  {
    id: "matsu-juguang",
    name: "莒光東莒",
    county: "連江縣",
    element: "metal",
    terrain: "海島燈塔",
    description: "馬祖最美的燈塔所在地，金靈能量在東犬燈塔的鐵鑄結構間凝聚，是旅人探索秘境的好地方。",
    landmarks: ["東犬燈塔", "東莒島", "西莒島", "莒光鄉公所"],
    dangerLevel: 4,
    connections: ["matsu-nangan"],
    travelTime: 80,
    monsterLevel: [10, 20],
    x: 9, y: 43,
  },
  {
    id: "matsu-dongyin",
    name: "東引燈塔",
    county: "連江縣",
    element: "metal",
    terrain: "海島要塞",
    description: "馬祖最北端的島嶼，金靈能量在東引燈塔的鐵鑄結構間凝聚，一線天是旅人探索秘境的終極挑戰。",
    landmarks: ["東引燈塔", "一線天", "安東坑道", "東引鄉公所"],
    dangerLevel: 4,
    connections: ["matsu-nangan"],
    travelTime: 90,
    monsterLevel: [11, 22],
    x: 9, y: 35,
  },
  {
    id: "matsu-qinbi",
    name: "芹壁聚落",
    county: "連江縣",
    element: "earth",
    terrain: "石屋聚落",
    description: "馬祖最美的傳統聚落，土靈能量在閩東式石屋的花崗岩間凝聚，是旅人感受馬祖文化的最佳地點。",
    landmarks: ["芹壁聚落", "芹壁天后宮", "芹壁海灣", "閩東式建築"],
    dangerLevel: 3,
    connections: ["matsu-beigan"],
    travelTime: 70,
    monsterLevel: [6, 15],
    x: 8, y: 37,
  },

  // ════════════════════════════════════════
  // 新竹縣（補充）
  // ════════════════════════════════════════
  {
    id: "hsinchu-xinpu",
    name: "新埔柿餅",
    county: "新竹縣",
    element: "fire",
    terrain: "客家農村",
    description: "柿餅的故鄉，火靈能量在曬柿餅的秋陽中升騰，新埔老街的百年宗祠是土靈的聖地。",
    landmarks: ["新埔柿餅", "新埔老街", "廣和宮", "九芎湖"],
    dangerLevel: 1,
    connections: ["hsinchu-zhudong", "taoyuan-yangmei"],
    travelTime: 35,
    monsterLevel: [2, 7],
    x: 35, y: 30,
  },
  {
    id: "hsinchu-guanxi",
    name: "關西老街",
    county: "新竹縣",
    element: "earth",
    terrain: "客家老街",
    description: "新竹最古老的客家聚落之一，土靈能量在百年老街的磚牆間流動，關西仙草是旅人的珍貴補給。",
    landmarks: ["關西老街", "關西仙草", "牛欄河親水公園", "關西車站"],
    dangerLevel: 2,
    connections: ["hsinchu-zhudong", "hsinchu-xinpu"],
    travelTime: 40,
    monsterLevel: [3, 8],
    x: 35, y: 29,
  },

  // ════════════════════════════════════════
  // 基隆（補充）
  // ════════════════════════════════════════
  {
    id: "xizhi-main",
    name: "汐止新市鎮",
    county: "新北市",
    element: "water",
    terrain: "河岸城鎮",
    description: "基隆河畔的新興城鎮，水靈在河流中流動，汐止老街保存著清代移民的記憶。",
    landmarks: ["汐止老街", "汐止車站", "基隆河", "汐止新市鎮"],
    dangerLevel: 1,
    connections: ["tp-neihu", "tp-nangang", "keelung-main"],
    travelTime: 30,
    monsterLevel: [1, 6],
    x: 54, y: 17,
  },

  // ════════════════════════════════════════
  // 新北（補充）
  // ════════════════════════════════════════
  {
    id: "xindian-main",
    name: "新店溪谷",
    county: "新北市",
    element: "water",
    terrain: "溪谷城區",
    description: "新店溪沿岸的城區，水靈在溪流中嬉戲，新店老街保存著清代移民的記憶。",
    landmarks: ["新店老街", "新店車站", "新店溪", "安坑"],
    dangerLevel: 1,
    connections: ["tp-wenshan", "tp-muzha", "tp-jingmei", "nb-xindian"],
    travelTime: 30,
    monsterLevel: [1, 6],
    x: 47, y: 26,
  },
  {
    id: "xindian-zhonghe",
    name: "中和景安",
    county: "新北市",
    element: "fire",
    terrain: "住宅商業區",
    description: "中和最熱鬧的商圈，火靈能量在景安夜市的爐火間跳動，是旅人補充體力的好地方。",
    landmarks: ["景安商圈", "景安捷運站", "中和老街", "中和公園"],
    dangerLevel: 1,
    connections: ["tp-wanhua", "nb-zhonghe", "nb-banqiao"],
    travelTime: 25,
    monsterLevel: [1, 5],
    x: 45, y: 22,
  },

  // ════════════════════════════════════════
  // 迷霧城（NPC 據點，台北市區）
  // ════════════════════════════════════════
  {
    id: "npc-fogcity-1",
    name: "迷霧城・戰士公會大廳",
    county: "迷霧城",
    element: "metal",
    terrain: "NPC據點",
    description: "帳篇市信義區的戰士公會，金屬氣息濃厚，連擊導師席拉在此授課。",
    landmarks: ["台北101", "信義商圈"],
    dangerLevel: 2,
    connections: ["tp-xinyi", "npc-fogcity-2", "npc-fogcity-6"],
    travelTime: 20,
    monsterLevel: [5, 20],
    x: 50, y: 19,
  },
  {
    id: "npc-fogcity-2",
    name: "迷霧城・武器評議塔",
    county: "迷霧城",
    element: "metal",
    terrain: "NPC據點",
    description: "圓山大飯店附近的武器評議塔，武器評議官沃克恩在此鑑定裝備。",
    landmarks: ["圓山大飯店", "中山北路"],
    dangerLevel: 2,
    connections: ["tp-zhongshan", "npc-fogcity-1", "npc-fogcity-7"],
    travelTime: 20,
    monsterLevel: [5, 20],
    x: 47, y: 17,
  },
  {
    id: "npc-fogcity-3",
    name: "迷霧城・東門箭塔",
    county: "迷霧城",
    element: "wood",
    terrain: "NPC據點",
    description: "中正紀念堂旁的箭塔，箭塔守衛艾拉在此訓練弓箭手。",
    landmarks: ["中正紀念堂", "自由廣場"],
    dangerLevel: 2,
    connections: ["tp-zhongzheng", "npc-fogcity-4"],
    travelTime: 20,
    monsterLevel: [5, 20],
    x: 47, y: 19,
  },
  {
    id: "npc-fogcity-4",
    name: "迷霧城・地下競技場",
    county: "迷霧城",
    element: "fire",
    terrain: "NPC據點",
    description: "龍山寺地下的秘密競技場，賭徒鬥士托里戈在此舉辦比武。",
    landmarks: ["龍山寺", "萬華商圈"],
    dangerLevel: 3,
    connections: ["tp-wanhua", "npc-fogcity-3", "npc-fogcity-5"],
    travelTime: 20,
    monsterLevel: [10, 30],
    x: 46, y: 20,
  },
  {
    id: "npc-fogcity-5",
    name: "迷霧城・黑市後巷",
    county: "迷霧城",
    element: "water",
    terrain: "NPC據點",
    description: "迪化街深處的黑市，暗影刺客暮在此出沒。",
    landmarks: ["迪化街", "大稻埕商圈"],
    dangerLevel: 3,
    connections: ["tp-datong", "npc-fogcity-4", "npc-fogcity-9"],
    travelTime: 20,
    monsterLevel: [10, 30],
    x: 46, y: 18,
  },
  {
    id: "npc-fogcity-6",
    name: "迷霧城・荒廢藥房",
    county: "迷霧城",
    element: "wood",
    terrain: "NPC據點",
    description: "松山文創園區內的荒廢藥房，毒術師維克多在此研究毒藥。",
    landmarks: ["松山文創園區", "信義商圈"],
    dangerLevel: 2,
    connections: ["tp-xinyi", "npc-fogcity-1"],
    travelTime: 20,
    monsterLevel: [5, 20],
    x: 50, y: 20,
  },
  {
    id: "npc-fogcity-7",
    name: "迷霧城・盜賊公會",
    county: "迷霧城",
    element: "water",
    terrain: "NPC據點",
    description: "林森北路深處的盜賊公會，盜賊首領洛克斯在此統率地下勢力。",
    landmarks: ["林森北路", "中山區"],
    dangerLevel: 3,
    connections: ["tp-zhongshan", "npc-fogcity-2", "npc-fogcity-8"],
    travelTime: 20,
    monsterLevel: [10, 30],
    x: 48, y: 17,
  },
  {
    id: "npc-fogcity-8",
    name: "迷霧城・採集者工會",
    county: "迷霧城",
    element: "wood",
    terrain: "NPC據點",
    description: "大安森林公園旁的採集者工會，公會長格林在此組織採集任務。",
    landmarks: ["大安森林公園", "大安區"],
    dangerLevel: 2,
    connections: ["tp-daan", "npc-fogcity-7"],
    travelTime: 20,
    monsterLevel: [5, 20],
    x: 48, y: 20,
  },
  {
    id: "npc-fogcity-9",
    name: "迷霧城・工匠街",
    county: "迷霧城",
    element: "fire",
    terrain: "NPC據點",
    description: "寧夏夜市附近的工匠街，工匠大師漢斯在此打造裝備。",
    landmarks: ["寧夏夜市", "大同區"],
    dangerLevel: 2,
    connections: ["tp-datong", "npc-fogcity-5", "npc-fogcity-10"],
    travelTime: 20,
    monsterLevel: [5, 20],
    x: 47, y: 18,
  },
  {
    id: "npc-fogcity-10",
    name: "迷霧城・鑑定商店",
    county: "迷霧城",
    element: "earth",
    terrain: "NPC據點",
    description: "饒河街夜市旁的鑑定商店，鑑定師瑪德琳在此提供鑑定服務。",
    landmarks: ["饒河街夜市", "松山區"],
    dangerLevel: 2,
    connections: ["tp-songshan", "npc-fogcity-9"],
    travelTime: 20,
    monsterLevel: [5, 20],
    x: 49, y: 18,
  },

  // ════════════════════════════════════════
  // 初界 NPC 據點（台灣各地）
  // ════════════════════════════════════════
  {
    id: "npc-realm1-11",
    name: "初界・試煉廣場",
    county: "初界",
    element: "fire",
    terrain: "NPC據點",
    description: "台大校園內的試煉廣場，火焰導師艾爾文・赤焰在此授課。",
    landmarks: ["台灣大學", "大安區"],
    dangerLevel: 1,
    connections: ["tp-daan", "npc-realm1-14"],
    travelTime: 20,
    monsterLevel: [1, 15],
    x: 48, y: 21,
  },
  {
    id: "npc-realm1-12",
    name: "初界・霜語小屋",
    county: "初界",
    element: "water",
    terrain: "NPC據點",
    description: "新竹科學園區附近的霜語小屋，冰霜魔女菲莉亞在此研究冰術。",
    landmarks: ["新竹科學園區"],
    dangerLevel: 1,
    connections: ["hsinchu-main"],
    travelTime: 30,
    monsterLevel: [5, 20],
    x: 35, y: 31,
  },
  {
    id: "npc-realm1-13",
    name: "初界・迷跡驛站",
    county: "初界",
    element: "wood",
    terrain: "NPC據點",
    description: "台中公園附近的迷跡驛站，風之旅者嵐德在此休憩。",
    landmarks: ["台中公園"],
    dangerLevel: 1,
    connections: ["taichung-main"],
    travelTime: 30,
    monsterLevel: [5, 25],
    x: 33, y: 42,
  },
  {
    id: "npc-realm1-14",
    name: "初界・學術廢墟",
    county: "初界",
    element: "water",
    terrain: "NPC據點",
    description: "碧潭附近的學術廢墟，催眠學者哈拉爾德在此研究精神魔法。",
    landmarks: ["碧潭", "新店區"],
    dangerLevel: 2,
    connections: ["nb-xindian", "npc-realm1-11"],
    travelTime: 25,
    monsterLevel: [10, 30],
    x: 48, y: 24,
  },
  {
    id: "npc-realm1-15",
    name: "初界・岩骨村",
    county: "初界",
    element: "earth",
    terrain: "NPC據點",
    description: "礁溪溫泉附近的岩骨村，石化術士格雷在此修煉。",
    landmarks: ["礁溪溫泉", "宜蘭縣"],
    dangerLevel: 2,
    connections: ["yilan-jiaoxi"],
    travelTime: 35,
    monsterLevel: [10, 30],
    x: 55, y: 25,
  },
  {
    id: "npc-realm1-16",
    name: "初界・濕毒沼澤",
    county: "初界",
    element: "water",
    terrain: "NPC據點",
    description: "鰇鼓濕地深處的毒沼，毒沼女巫米莉亞在此研究毒術。",
    landmarks: ["鰇鼓濕地", "嘉義縣"],
    dangerLevel: 2,
    connections: ["chiayi-main"],
    travelTime: 35,
    monsterLevel: [10, 30],
    x: 28, y: 52,
  },
  {
    id: "npc-realm1-17",
    name: "初界・回憶沙漠",
    county: "初界",
    element: "fire",
    terrain: "NPC據點",
    description: "七股鹽山附近的回憶沙漠，艾爾文的幽靈在此徘徊。",
    landmarks: ["七股鹽山", "台南市"],
    dangerLevel: 2,
    connections: ["tainan-main"],
    travelTime: 35,
    monsterLevel: [10, 30],
    x: 26, y: 55,
  },
  {
    id: "npc-realm1-18",
    name: "初界・葡萄酒莊",
    county: "初界",
    element: "wood",
    terrain: "NPC據點",
    description: "鹿港老街附近的葡萄酒莊，商人露西在此經營。",
    landmarks: ["鹿港老街", "彰化縣"],
    dangerLevel: 1,
    connections: ["changhua-lugang"],
    travelTime: 30,
    monsterLevel: [5, 25],
    x: 30, y: 44,
  },
  {
    id: "npc-realm1-19",
    name: "初界・聖光修道院",
    county: "初界",
    element: "metal",
    terrain: "NPC據點",
    description: "阿里山森林中的聖光修道院，聖光修士艾文與治癒師琳娜在此修行。",
    landmarks: ["阿里山", "嘉義市"],
    dangerLevel: 3,
    connections: ["chiayi-alishan"],
    travelTime: 40,
    monsterLevel: [15, 40],
    x: 29, y: 50,
  },
  {
    id: "npc-realm1-20",
    name: "初界・泉水聖所",
    county: "初界",
    element: "water",
    terrain: "NPC據點",
    description: "蓮池潭旁的泉水聖所，淨化聖女索菲亞在此淨化靈魂。",
    landmarks: ["蓮池潭", "高雄市"],
    dangerLevel: 2,
    connections: ["kaohsiung-zuoying", "npc-realm2-21"],
    travelTime: 35,
    monsterLevel: [10, 30],
    x: 25, y: 60,
  },

  // ════════════════════════════════════════
  // 中界 NPC 據點（海外：日本・韓國・中國）
  // ════════════════════════════════════════
  {
    id: "npc-realm2-21",
    name: "中界・墜星高地",
    county: "中界",
    element: "fire",
    terrain: "NPC據點",
    description: "日本富士山附近的墜星高地，火焰戰士凱恩在此修煉。",
    landmarks: ["富士山", "日本"],
    dangerLevel: 4,
    connections: ["npc-realm1-20", "npc-realm2-22", "npc-realm2-26"],
    travelTime: 60,
    monsterLevel: [30, 60],
    x: 80, y: 10,
  },
  {
    id: "npc-realm2-22",
    name: "中界・混沌實驗室",
    county: "中界",
    element: "water",
    terrain: "NPC據點",
    description: "東京秋葉原地下的混沌實驗室，研究員奧利弗在此進行實驗。",
    landmarks: ["秋葉原", "東京"],
    dangerLevel: 4,
    connections: ["npc-realm2-21", "npc-realm2-27"],
    travelTime: 60,
    monsterLevel: [30, 55],
    x: 82, y: 8,
  },
  {
    id: "npc-realm2-23",
    name: "中界・永恆教堂",
    county: "中界",
    element: "metal",
    terrain: "NPC據點",
    description: "韓國首爾景福宮內的永恆教堂，復活祭司馬修在此修行。",
    landmarks: ["景福宮", "首爾"],
    dangerLevel: 4,
    connections: ["npc-realm2-29"],
    travelTime: 60,
    monsterLevel: [35, 65],
    x: 75, y: 12,
  },
  {
    id: "npc-realm2-24",
    name: "中界・古老森林",
    county: "中界",
    element: "wood",
    terrain: "NPC據點",
    description: "中國杭州西湖旁的古老森林，森林治癒者蓮娜在此研究草藥。",
    landmarks: ["西湖", "杭州"],
    dangerLevel: 4,
    connections: ["npc-realm2-25"],
    travelTime: 60,
    monsterLevel: [30, 55],
    x: 70, y: 20,
  },
  {
    id: "npc-realm2-25",
    name: "中界・影之山谷",
    county: "中界",
    element: "water",
    terrain: "NPC據點",
    description: "中國重慶武隆天生三橋附近的影之山谷，影之吸收者塔洛斯在此修煉。",
    landmarks: ["天生三橋", "重慶"],
    dangerLevel: 5,
    connections: ["npc-realm2-24"],
    travelTime: 70,
    monsterLevel: [40, 70],
    x: 65, y: 22,
  },
  {
    id: "npc-realm2-26",
    name: "中界・虛空法塔",
    county: "中界",
    element: "fire",
    terrain: "NPC據點",
    description: "日本大阪城內的虛空法塔，虛空法師艾莉絲在此研究空間魔法。",
    landmarks: ["大阪城", "大阪"],
    dangerLevel: 4,
    connections: ["npc-realm2-21", "npc-realm2-28"],
    travelTime: 60,
    monsterLevel: [35, 65],
    x: 78, y: 12,
  },
  {
    id: "npc-realm2-27",
    name: "中界・鏡之修行場",
    county: "中界",
    element: "water",
    terrain: "NPC據點",
    description: "日本長野善光寺附近的修行場，鏡之修行者靜源在此冥想。",
    landmarks: ["善光寺", "長野"],
    dangerLevel: 4,
    connections: ["npc-realm2-22"],
    travelTime: 60,
    monsterLevel: [35, 60],
    x: 80, y: 6,
  },
  {
    id: "npc-realm2-28",
    name: "中界・暗影公會",
    county: "中界",
    element: "water",
    terrain: "NPC據點",
    description: "日本京都伏見稻荷大社地下的暗影公會，暗殺大師夜歌在此統率刺客。",
    landmarks: ["伏見稻荷大社", "京都"],
    dangerLevel: 5,
    connections: ["npc-realm2-26"],
    travelTime: 60,
    monsterLevel: [40, 70],
    x: 78, y: 10,
  },
  {
    id: "npc-realm2-29",
    name: "中界・永恆殿堂",
    county: "中界",
    element: "metal",
    terrain: "NPC據點",
    description: "韓國首爾昌德宮內的永恆殿堂，聖盾騎士雷納德在此守護。",
    landmarks: ["昌德宮", "首爾"],
    dangerLevel: 5,
    connections: ["npc-realm2-23"],
    travelTime: 60,
    monsterLevel: [45, 75],
    x: 75, y: 11,
  },

  // ════════════════════════════════════════
  // 試煉之塔（瑞士・少女峰）
  // ════════════════════════════════════════
  {
    id: "npc-tower-30",
    name: "試煉之塔・地下訓練場",
    county: "試煉之塔",
    element: "earth",
    terrain: "NPC據點",
    description: "瑞士少女峰地下的訓練場，守護者在此訓練最強的戰士。",
    landmarks: ["少女峰", "瑞士阿爾卑斯山"],
    dangerLevel: 5,
    connections: ["npc-realm2-21"],
    travelTime: 120,
    monsterLevel: [50, 99],
    x: 55, y: 2,
  },

  // ════════════════════════════════════════
  // 碎影深淵（尼泊爾・聖母峰基地營）
  // ════════════════════════════════════════
  {
    id: "npc-abyss-31",
    name: "碎影深淵・入口營地",
    county: "碎影深淵",
    element: "metal",
    terrain: "NPC據點",
    description: "尼泊爾聖母峰基地營的入口，深淵守衞在此看守通往深淵的通道。",
    landmarks: ["聖母峰基地營", "尼泊爾喜馬拉雅"],
    dangerLevel: 5,
    connections: ["npc-tower-30"],
    travelTime: 150,
    monsterLevel: [60, 99],
    x: 50, y: 5,
  },
];

// ─── 查詢工具 ─────────────────────────────────────────────
export const MAP_NODE_MAP = new Map<string, MapNode>(
  MAP_NODES.map((n) => [n.id, n])
);

// 五行相剋關係
export const WUXING_OVERCOME: Record<WuXing, WuXing> = {
  wood: "earth",  // 木剋土
  earth: "water", // 土剋水
  water: "fire",  // 水剋火
  fire: "metal",  // 火剋金
  metal: "wood",  // 金剋木
};

// 五行相生關係
export const WUXING_GENERATE: Record<WuXing, WuXing> = {
  wood: "fire",   // 木生火
  fire: "earth",  // 火生土
  earth: "metal", // 土生金
  metal: "water", // 金生水
  water: "wood",  // 水生木
};

// 計算五行加成倍率
export function calcWuxingMultiplier(attacker: WuXing, defender: WuXing): number {
  if (WUXING_OVERCOME[attacker] === defender) return 1.5; // 相剋：傷害 +50%
  if (WUXING_OVERCOME[defender] === attacker) return 0.7; // 被剋：傷害 -30%
  if (WUXING_GENERATE[attacker] === defender) return 1.2; // 相生：傷害 +20%
  return 1.0;
}

// 今日流日元素（根據農曆天干）
export function getDailyElement(stem: string): WuXing {
  const stemMap: Record<string, WuXing> = {
    甲: "wood", 乙: "wood",
    丙: "fire", 丁: "fire",
    戊: "earth", 己: "earth",
    庚: "metal", 辛: "metal",
    壬: "water", 癸: "water",
  };
  return stemMap[stem] ?? "earth";
}


// ─────────────────────────────────────────────
// 距離制移動體力消耗系統
// ─────────────────────────────────────────────

/**
 * 計算兩節點之間的歐幾里得距離（基於 x,y 座標，0-100 範圍）
 */
export function calcNodeDistance(fromNode: MapNode, toNode: MapNode): number {
  const dx = toNode.x - fromNode.x;
  const dy = toNode.y - fromNode.y;
  return Math.sqrt(dx * dx + dy * dy);
}

/**
 * 計算移動體力消耗
 * 公式：
 *   - 基礎消耗：2 點
 *   - 距離加成：每超過 5 個單位距離，額外 +1 點（向上取整）
 *   - 危險等級加成：目標節點 dangerLevel × 0.5（向下取整）
 *   - 最小消耗：2 點，最大消耗：12 點
 *
 * 範例：
 *   - 相鄰節點（距離 ~3）：2 點
 *   - 中距離（距離 ~10）：2 + 2 = 4 點
 *   - 遠距離（距離 ~20）：2 + 4 = 6 點
 *   - 跨縣市（距離 ~30）：2 + 6 = 8 點
 */
export function calcMoveCost(fromNode: MapNode, toNode: MapNode): number {
  const dist = calcNodeDistance(fromNode, toNode);
  const distBonus = Math.ceil(dist / 5);
  const dangerBonus = Math.floor(toNode.dangerLevel * 0.5);
  const total = 2 + distBonus + dangerBonus;
  return Math.max(2, Math.min(12, total));
}

/**
 * 取得移動體力消耗的文字描述（用於前端顯示）
 */
export function getMoveCostLabel(cost: number): string {
  if (cost <= 2) return '近距離（-2 體力）';
  if (cost <= 4) return '短途（-' + cost + ' 體力）';
  if (cost <= 6) return '中途（-' + cost + ' 體力）';
  if (cost <= 8) return '長途（-' + cost + ' 體力）';
  return '遠征（-' + cost + ' 體力）';
}
