INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_W001', '葉刃狐', '木', '3-3', 'common',
  120, 15, 8, 25, 20, 10,
  20, 30, 10, 20, 15, 20,
  'SK_M001', '', '',
  1, 1.0,
  'I_W001', 15.0, '{"min": 80, "max": 150}',
  '', 0.0,
  1, 1774397303771
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_W002', '藤蔓蜘蛛', '木', '4-4', 'common',
  95, 14, 12, 18, 18, 8,
  25, 15, 20, 15, 10, 15,
  'SK_M003', 'SK_M002', '',
  1, 1.0,
  'I_W002', 20.0, '{"min": 80, "max": 150}',
  '', 0.0,
  1, 1774397303771
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_W003', '綠芽史萊姆', '木', '1-1', 'common',
  150, 8, 15, 10, 12, 5,
  30, 10, 15, 20, 15, 15,
  'SK_M004', '', '',
  1, 1.0,
  'I_W003', 25.0, '{"min": 50, "max": 100}',
  '', 0.0,
  1, 1774397303771
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_W004', '刺刺蝟', '木', '5-5', 'common',
  110, 18, 10, 15, 20, 8,
  20, 25, 15, 15, 10, 15,
  'SK_M005', '', '',
  1, 1.2,
  'I_W004', 18.0, '{"min": 100, "max": 180}',
  '', 0.0,
  1, 1774397303771
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_W005', '孢子菇', '木', '2-2', 'common',
  80, 12, 8, 12, 15, 18,
  35, 5, 10, 15, 20, 20,
  'SK_M006', '', '',
  1, 1.0,
  'I_W005', 22.0, '{"min": 60, "max": 120}',
  '', 0.0,
  1, 1774397303771
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_W006', '樹皮甲蟲', '木', '6-6', 'common',
  140, 10, 20, 8, 15, 5,
  25, 15, 25, 10, 10, 15,
  'SK_M007', '', '',
  1, 1.2,
  'I_W006', 18.0, '{"min": 100, "max": 200}',
  '', 0.0,
  1, 1774397303771
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_W007', '飛葉蝶', '木', '3-3', 'common',
  70, 20, 5, 35, 25, 12,
  30, 10, 10, 25, 15, 20,
  'SK_M008', '', '',
  1, 1.2,
  'I_W007', 15.0, '{"min": 80, "max": 150}',
  '', 0.0,
  1, 1774397303771
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_W008', '泥沼蛙', '木', '4-4', 'common',
  130, 12, 15, 14, 16, 8,
  20, 15, 20, 15, 25, 20,
  'SK_M009', '', '',
  1, 1.0,
  'I_W008', 20.0, '{"min": 80, "max": 140}',
  '', 0.0,
  1, 1774397303771
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_W009', '纏繞草蛇', '木', '5-5', 'common',
  100, 16, 10, 22, 22, 10,
  25, 20, 15, 15, 15, 20,
  'SK_M010', '', '',
  1, 1.0,
  'I_W009', 18.0, '{"min": 100, "max": 180}',
  '', 0.0,
  1, 1774397303771
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_W010', '枯木妖', '木', '7-7', 'common',
  160, 14, 18, 5, 12, 10,
  30, 5, 25, 10, 15, 25,
  'SK_M011', '', '',
  1, 1.2,
  'I_W010', 15.0, '{"min": 120, "max": 220}',
  '', 0.0,
  1, 1774397303771
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
