INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_Wt008', '冰晶蝶', '水', '5-5', 'common',
  65, 16, 4, 32, 18, 28,
  12, 35, 8, 8, 38, 20,
  '', '', '',
  1, 1.2,
  '', 15.0, '{"min": 95, "max": 180}',
  '', 0.0,
  1, 1774397303772
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_Wt009', '河豚', '水', '6-6', 'common',
  130, 15, 10, 8, 15, 12,
  12, 22, 12, 10, 30, 15,
  '', '', '',
  1, 1.0,
  '', 12.0, '{"min": 102, "max": 195}',
  '', 0.0,
  1, 1774397303772
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_Wt010', '水蛇', '水', '7-7', 'common',
  105, 16, 10, 25, 20, 14,
  12, 25, 10, 8, 30, 15,
  '', '', '',
  1, 1.0,
  '', 18.0, '{"min": 118, "max": 225}',
  '', 0.0,
  1, 1774397303772
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_Wt011', '水元素', '水', '15-15', 'rare',
  300, 28, 15, 32, 30, 45,
  15, 35, 12, 10, 48, 25,
  '', '', '',
  2, 1.2,
  '', 20.0, '{"min": 340, "max": 545}',
  '', 0.0,
  1, 1774397303772
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_Wt012', '冰晶史萊姆', '水', '16-16', 'rare',
  280, 22, 12, 25, 25, 48,
  12, 40, 10, 10, 50, 25,
  '', '', '',
  2, 1.2,
  '', 18.0, '{"min": 355, "max": 568}',
  '', 0.0,
  1, 1774397303772
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_Wt013', '水母群', '水', '14-14', 'rare',
  350, 25, 20, 22, 28, 38,
  15, 32, 12, 10, 45, 20,
  '', '', '',
  2, 1.2,
  '', 22.0, '{"min": 305, "max": 488}',
  '', 0.0,
  1, 1774397303772
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_Wt014', '海浪龜', '水', '18-18', 'rare',
  500, 22, 40, 8, 22, 30,
  15, 25, 15, 10, 50, 30,
  '', '', '',
  2, 1.2,
  '', 20.0, '{"min": 405, "max": 648}',
  '', 0.0,
  1, 1774397303772
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_Wt015', '劍魚', '水', '20-20', 'rare',
  260, 52, 10, 42, 42, 18,
  10, 30, 10, 10, 42, 20,
  '', '', '',
  2, 1.5,
  '', 15.0, '{"min": 425, "max": 680}',
  '', 0.0,
  1, 1774397303772
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_Wt016', '冰霜狼', '水', '19-19', 'rare',
  320, 42, 15, 35, 38, 25,
  12, 38, 10, 10, 45, 20,
  '', '', '',
  2, 1.2,
  '', 18.0, '{"min": 415, "max": 664}',
  '', 0.0,
  1, 1774397303772
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
INSERT INTO game_monster_catalog (
  monster_id, name, wuxing, level_range, rarity,
  base_hp, base_attack, base_defense, base_speed, base_accuracy, base_magic_attack,
  resist_wood, resist_fire, resist_earth, resist_metal, resist_water, counter_bonus,
  skill_id_1, skill_id_2, skill_id_3,
  ai_level, growth_rate,
  drop_item_1, drop_rate_1, drop_gold,
  legendary_drop, legendary_drop_rate,
  is_active, created_at
) VALUES (
  'M_Wt017', '海妖', '水', '22-22', 'rare',
  290, 38, 12, 30, 35, 52,
  15, 35, 10, 10, 48, 20,
  '', '', '',
  2, 1.5,
  '', 15.0, '{"min": 465, "max": 744}',
  '', 0.0,
  1, 1774397303772
) ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  wuxing = VALUES(wuxing),
  level_range = VALUES(level_range),
  rarity = VALUES(rarity),
  base_hp = VALUES(base_hp),
  base_attack = VALUES(base_attack),
  base_defense = VALUES(base_defense),
  base_speed = VALUES(base_speed),
  base_accuracy = VALUES(base_accuracy),
  base_magic_attack = VALUES(base_magic_attack),
  resist_wood = VALUES(resist_wood),
  resist_fire = VALUES(resist_fire),
  resist_earth = VALUES(resist_earth),
  resist_metal = VALUES(resist_metal),
  resist_water = VALUES(resist_water),
  counter_bonus = VALUES(counter_bonus),
  skill_id_1 = VALUES(skill_id_1),
  skill_id_2 = VALUES(skill_id_2),
  skill_id_3 = VALUES(skill_id_3),
  ai_level = VALUES(ai_level),
  growth_rate = VALUES(growth_rate),
  drop_item_1 = VALUES(drop_item_1),
  drop_rate_1 = VALUES(drop_rate_1),
  drop_gold = VALUES(drop_gold),
  legendary_drop = VALUES(legendary_drop),
  legendary_drop_rate = VALUES(legendary_drop_rate);
